/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type KnowledgeBaseResponse,
    KnowledgeBaseResponseFromJSON,
    KnowledgeBaseResponseToJSON,
} from '../models/KnowledgeBaseResponse';
import {
    type KnowledgeDocumentResponse,
    KnowledgeDocumentResponseFromJSON,
    KnowledgeDocumentResponseToJSON,
} from '../models/KnowledgeDocumentResponse';

export interface PublicDeleteDocumentRequest {
    id: string;
}

export interface PublicGetDocumentRequest {
    id: string;
}

export interface PublicGetKnowledgeBaseRequest {
    slug: string;
}

export interface PublicUploadDocumentsRequest {
    slug: string;
    files?: Array<Blob>;
}

/**
 * 
 */
export class KnowledgeBasesApi extends runtime.BaseAPI {

    /**
     * Creates request options for publicDeleteDocument without sending the request
     */
    async publicDeleteDocumentRequestOpts(requestParameters: PublicDeleteDocumentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publicDeleteDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/knowledge-documents/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permanently removes a document and all its chunks from the knowledge base. Search results will no longer include content from this document.
     * Delete a knowledge document
     */
    async publicDeleteDocumentRaw(requestParameters: PublicDeleteDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.publicDeleteDocumentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently removes a document and all its chunks from the knowledge base. Search results will no longer include content from this document.
     * Delete a knowledge document
     */
    async publicDeleteDocument(requestParameters: PublicDeleteDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.publicDeleteDocumentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for publicGetDocument without sending the request
     */
    async publicGetDocumentRequestOpts(requestParameters: PublicGetDocumentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publicGetDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/knowledge-documents/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a single document with its processing status, file name, size, and chunk count. Use this to check whether a recently uploaded document has finished indexing.
     * Get a knowledge document by ID
     */
    async publicGetDocumentRaw(requestParameters: PublicGetDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KnowledgeDocumentResponse>> {
        const requestOptions = await this.publicGetDocumentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KnowledgeDocumentResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a single document with its processing status, file name, size, and chunk count. Use this to check whether a recently uploaded document has finished indexing.
     * Get a knowledge document by ID
     */
    async publicGetDocument(requestParameters: PublicGetDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KnowledgeDocumentResponse> {
        const response = await this.publicGetDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicGetKnowledgeBase without sending the request
     */
    async publicGetKnowledgeBaseRequestOpts(requestParameters: PublicGetKnowledgeBaseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling publicGetKnowledgeBase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/knowledge-bases/{slug}`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a knowledge base with its processing status, document count, chunk count, and a list of all documents. Use this to verify that uploaded documents have finished indexing before relying on them in prompts.
     * Get a knowledge base by slug
     */
    async publicGetKnowledgeBaseRaw(requestParameters: PublicGetKnowledgeBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KnowledgeBaseResponse>> {
        const requestOptions = await this.publicGetKnowledgeBaseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KnowledgeBaseResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a knowledge base with its processing status, document count, chunk count, and a list of all documents. Use this to verify that uploaded documents have finished indexing before relying on them in prompts.
     * Get a knowledge base by slug
     */
    async publicGetKnowledgeBase(requestParameters: PublicGetKnowledgeBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KnowledgeBaseResponse> {
        const response = await this.publicGetKnowledgeBaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicUploadDocuments without sending the request
     */
    async publicUploadDocumentsRequestOpts(requestParameters: PublicUploadDocumentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling publicUploadDocuments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['files'] != null) {
            requestParameters['files'].forEach((element) => {
                formParams.append('files', element as any);
            })
        }


        let urlPath = `/api/v1/knowledge-bases/{slug}/documents`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Uploads one or more files to a knowledge base for chunking and embedding. Documents are processed asynchronously. Listen for the knowledgedocument.finished webhook or poll the document endpoint to know when they are searchable.
     * Upload documents to a knowledge base
     */
    async publicUploadDocumentsRaw(requestParameters: PublicUploadDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KnowledgeDocumentResponse>>> {
        const requestOptions = await this.publicUploadDocumentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KnowledgeDocumentResponseFromJSON));
    }

    /**
     * Uploads one or more files to a knowledge base for chunking and embedding. Documents are processed asynchronously. Listen for the knowledgedocument.finished webhook or poll the document endpoint to know when they are searchable.
     * Upload documents to a knowledge base
     */
    async publicUploadDocuments(requestParameters: PublicUploadDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KnowledgeDocumentResponse>> {
        const response = await this.publicUploadDocumentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
