/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreatePromptRun,
    CreatePromptRunFromJSON,
    CreatePromptRunToJSON,
} from '../models/CreatePromptRun';
import {
    type CreatePromptRunResponse,
    CreatePromptRunResponseFromJSON,
    CreatePromptRunResponseToJSON,
} from '../models/CreatePromptRunResponse';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type GetPromptRevisionVersionParameter,
    GetPromptRevisionVersionParameterFromJSON,
    GetPromptRevisionVersionParameterToJSON,
} from '../models/GetPromptRevisionVersionParameter';
import {
    type PromptRun,
    PromptRunFromJSON,
    PromptRunToJSON,
} from '../models/PromptRun';

export interface CreatePromptRunRequest {
    slug: string;
    version: GetPromptRevisionVersionParameter;
    createPromptRun: CreatePromptRun;
}

export interface GetPromptRunRequest {
    id: string;
}

/**
 * 
 */
export class PromptRunsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPromptRun without sending the request
     */
    async createPromptRunRequestOpts(requestParameters: CreatePromptRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling createPromptRun().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling createPromptRun().'
            );
        }

        if (requestParameters['createPromptRun'] == null) {
            throw new runtime.RequiredError(
                'createPromptRun',
                'Required parameter "createPromptRun" was null or undefined when calling createPromptRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/prompts/{slug}/{version}/runs`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePromptRunToJSON(requestParameters['createPromptRun']),
        };
    }

    /**
     * Triggers an asynchronous prompt run with the given inputs and returns a run ID and thread ID. Reference the prompt by version number, tag, or `__latest__`. Pass a thread ID to continue an existing conversation.
     * Create and trigger a prompt run
     */
    async createPromptRunRaw(requestParameters: CreatePromptRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePromptRunResponse>> {
        const requestOptions = await this.createPromptRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePromptRunResponseFromJSON(jsonValue));
    }

    /**
     * Triggers an asynchronous prompt run with the given inputs and returns a run ID and thread ID. Reference the prompt by version number, tag, or `__latest__`. Pass a thread ID to continue an existing conversation.
     * Create and trigger a prompt run
     */
    async createPromptRun(requestParameters: CreatePromptRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePromptRunResponse> {
        const response = await this.createPromptRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPromptRun without sending the request
     */
    async getPromptRunRequestOpts(requestParameters: GetPromptRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPromptRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/promptruns/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the current state of a prompt run, including status, outputs, token usage, cost, and errors. Poll this endpoint after receiving a webhook notification, or use it to check the status of a run in progress.
     * Get a prompt run by ID
     */
    async getPromptRunRaw(requestParameters: GetPromptRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromptRun>> {
        const requestOptions = await this.getPromptRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromptRunFromJSON(jsonValue));
    }

    /**
     * Retrieves the current state of a prompt run, including status, outputs, token usage, cost, and errors. Poll this endpoint after receiving a webhook notification, or use it to check the status of a run in progress.
     * Get a prompt run by ID
     */
    async getPromptRun(requestParameters: GetPromptRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromptRun> {
        const response = await this.getPromptRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
