/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetPromptRevisionVersionParameter,
    GetPromptRevisionVersionParameterFromJSON,
    GetPromptRevisionVersionParameterToJSON,
} from '../models/GetPromptRevisionVersionParameter';
import {
    type PromptRevision,
    PromptRevisionFromJSON,
    PromptRevisionToJSON,
} from '../models/PromptRevision';

export interface GetPromptRevisionRequest {
    slug: string;
    version: GetPromptRevisionVersionParameter;
}

/**
 * 
 */
export class PromptsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPromptRevision without sending the request
     */
    async getPromptRevisionRequestOpts(requestParameters: GetPromptRevisionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getPromptRevision().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling getPromptRevision().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/prompts/{slug}/{version}`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the full configuration of a prompt revision including model, parameters, tool calls, messages.
     * Get a prompt revision by the prompt’s slug and version
     */
    async getPromptRevisionRaw(requestParameters: GetPromptRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromptRevision>> {
        const requestOptions = await this.getPromptRevisionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromptRevisionFromJSON(jsonValue));
    }

    /**
     * Retrieves the full configuration of a prompt revision including model, parameters, tool calls, messages.
     * Get a prompt revision by the prompt’s slug and version
     */
    async getPromptRevision(requestParameters: GetPromptRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromptRevision> {
        const response = await this.getPromptRevisionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
