/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type StreamTokenResponse,
    StreamTokenResponseFromJSON,
    StreamTokenResponseToJSON,
} from '../models/StreamTokenResponse';

export interface CreateStreamTokenRequest {
    thread: string;
}

/**
 * 
 */
export class StreamingApi extends runtime.BaseAPI {

    /**
     * Creates request options for createStreamToken without sending the request
     */
    async createStreamTokenRequestOpts(requestParameters: CreateStreamTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['thread'] == null) {
            throw new runtime.RequiredError(
                'thread',
                'Required parameter "thread" was null or undefined when calling createStreamToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/threads/{thread}/stream-token`;
        urlPath = urlPath.replace('{thread}', encodeURIComponent(String(requestParameters['thread'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a short-lived, thread-scoped token your frontend can use to subscribe to live token output over SSE. Call this from your backend with your API key, then hand the token to the browser — the API key itself must never leave your server. The thread does not have to exist yet: mint a token, connect, then start the run. Connect before triggering a run, since tokens emitted while nobody is subscribed are not replayed.
     * Create a streaming credential for a thread
     */
    async createStreamTokenRaw(requestParameters: CreateStreamTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreamTokenResponse>> {
        const requestOptions = await this.createStreamTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreamTokenResponseFromJSON(jsonValue));
    }

    /**
     * Returns a short-lived, thread-scoped token your frontend can use to subscribe to live token output over SSE. Call this from your backend with your API key, then hand the token to the browser — the API key itself must never leave your server. The thread does not have to exist yet: mint a token, connect, then start the run. Connect before triggering a run, since tokens emitted while nobody is subscribed are not replayed.
     * Create a streaming credential for a thread
     */
    async createStreamToken(requestParameters: CreateStreamTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreamTokenResponse> {
        const response = await this.createStreamTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
