/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateWorkflowRun,
    CreateWorkflowRunFromJSON,
    CreateWorkflowRunToJSON,
} from '../models/CreateWorkflowRun';
import {
    type CreateWorkflowRunResponse,
    CreateWorkflowRunResponseFromJSON,
    CreateWorkflowRunResponseToJSON,
} from '../models/CreateWorkflowRunResponse';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type GetPromptRevisionVersionParameter,
    GetPromptRevisionVersionParameterFromJSON,
    GetPromptRevisionVersionParameterToJSON,
} from '../models/GetPromptRevisionVersionParameter';
import {
    type WorkflowRun,
    WorkflowRunFromJSON,
    WorkflowRunToJSON,
} from '../models/WorkflowRun';

export interface CreateWorkflowRunRequest {
    slug: string;
    version: GetPromptRevisionVersionParameter;
    createWorkflowRun: CreateWorkflowRun;
}

export interface GetWorkflowRunRequest {
    id: string;
}

/**
 * 
 */
export class WorkflowRunsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createWorkflowRun without sending the request
     */
    async createWorkflowRunRequestOpts(requestParameters: CreateWorkflowRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling createWorkflowRun().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling createWorkflowRun().'
            );
        }

        if (requestParameters['createWorkflowRun'] == null) {
            throw new runtime.RequiredError(
                'createWorkflowRun',
                'Required parameter "createWorkflowRun" was null or undefined when calling createWorkflowRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/workflows/{slug}/{version}/runs`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkflowRunToJSON(requestParameters['createWorkflowRun']),
        };
    }

    /**
     * Triggers an asynchronous workflow run with the given inputs and returns a run ID and thread ID. Reference the workflow by version number, tag, or `__latest__`. Pass a thread ID to continue an existing conversation across runs.
     * Create and trigger a workflow run
     */
    async createWorkflowRunRaw(requestParameters: CreateWorkflowRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWorkflowRunResponse>> {
        const requestOptions = await this.createWorkflowRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateWorkflowRunResponseFromJSON(jsonValue));
    }

    /**
     * Triggers an asynchronous workflow run with the given inputs and returns a run ID and thread ID. Reference the workflow by version number, tag, or `__latest__`. Pass a thread ID to continue an existing conversation across runs.
     * Create and trigger a workflow run
     */
    async createWorkflowRun(requestParameters: CreateWorkflowRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWorkflowRunResponse> {
        const response = await this.createWorkflowRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWorkflowRun without sending the request
     */
    async getWorkflowRunRequestOpts(requestParameters: GetWorkflowRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkflowRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/workflowruns/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the current state of a workflow run, including status, outputs, aggregated token usage, cost, and errors. Poll this endpoint after receiving a webhook notification, or use it to check the status of a run in progress.
     * Get a workflow run by ID
     */
    async getWorkflowRunRaw(requestParameters: GetWorkflowRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowRun>> {
        const requestOptions = await this.getWorkflowRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowRunFromJSON(jsonValue));
    }

    /**
     * Retrieves the current state of a workflow run, including status, outputs, aggregated token usage, cost, and errors. Poll this endpoint after receiving a webhook notification, or use it to check the status of a run in progress.
     * Get a workflow run by ID
     */
    async getWorkflowRun(requestParameters: GetWorkflowRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowRun> {
        const response = await this.getWorkflowRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
