/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A source the model cited.
 * @export
 * @interface Citation
 */
export interface Citation {
    /**
     * 
     * @type {string}
     * @memberof Citation
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Citation
     */
    url: string;
}

/**
 * Check if a given object implements the Citation interface.
 */
export function instanceOfCitation(value: object): value is Citation {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CitationFromJSON(json: any): Citation {
    return CitationFromJSONTyped(json, false);
}

export function CitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Citation {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'url': json['url'],
    };
}

export function CitationToJSON(json: any): Citation {
    return CitationToJSONTyped(json, false);
}

export function CitationToJSONTyped(value?: Citation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'url': value['url'],
    };
}

