/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';

/**
 * User or assistant message.
 * @export
 * @interface ContentMessageResponse
 */
export interface ContentMessageResponse {
    /**
     * Message direction / role.
     * @type {Role}
     * @memberof ContentMessageResponse
     */
    role: Role;
    /**
     * Message content.
     * @type {string}
     * @memberof ContentMessageResponse
     */
    content: string;
}



/**
 * Check if a given object implements the ContentMessageResponse interface.
 */
export function instanceOfContentMessageResponse(value: object): value is ContentMessageResponse {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ContentMessageResponseFromJSON(json: any): ContentMessageResponse {
    return ContentMessageResponseFromJSONTyped(json, false);
}

export function ContentMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'role': RoleFromJSON(json['role']),
        'content': json['content'],
    };
}

export function ContentMessageResponseToJSON(json: any): ContentMessageResponse {
    return ContentMessageResponseToJSONTyped(json, false);
}

export function ContentMessageResponseToJSONTyped(value?: ContentMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': RoleToJSON(value['role']),
        'content': value['content'],
    };
}

