/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type CreateWorkflowRunMetadataValue
 * 
 * @export
 */
export type CreateWorkflowRunMetadataValue = Array<string> | string;

export function CreateWorkflowRunMetadataValueFromJSON(json: any): CreateWorkflowRunMetadataValue {
    return CreateWorkflowRunMetadataValueFromJSONTyped(json, false);
}

export function CreateWorkflowRunMetadataValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkflowRunMetadataValue {
    if (json == null) {
        return json;
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'string')) {
            return json;
        }
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function CreateWorkflowRunMetadataValueToJSON(json: any): any {
    return CreateWorkflowRunMetadataValueToJSONTyped(json, false);
}

export function CreateWorkflowRunMetadataValueToJSONTyped(value?: CreateWorkflowRunMetadataValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'string')) {
            return value;
        }
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

