/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkflowRunResponse
 */
export interface CreateWorkflowRunResponse {
    /**
     * Workflow run ID
     * @type {string}
     * @memberof CreateWorkflowRunResponse
     */
    id: string;
    /**
     * Thread ID for multi-turn runs
     * @type {string}
     * @memberof CreateWorkflowRunResponse
     */
    thread: string;
}

/**
 * Check if a given object implements the CreateWorkflowRunResponse interface.
 */
export function instanceOfCreateWorkflowRunResponse(value: object): value is CreateWorkflowRunResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('thread' in value) || value['thread'] === undefined) return false;
    return true;
}

export function CreateWorkflowRunResponseFromJSON(json: any): CreateWorkflowRunResponse {
    return CreateWorkflowRunResponseFromJSONTyped(json, false);
}

export function CreateWorkflowRunResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkflowRunResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'thread': json['thread'],
    };
}

export function CreateWorkflowRunResponseToJSON(json: any): CreateWorkflowRunResponse {
    return CreateWorkflowRunResponseToJSONTyped(json, false);
}

export function CreateWorkflowRunResponseToJSONTyped(value?: CreateWorkflowRunResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'thread': value['thread'],
    };
}

