/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePromptRunResponse
 */
export interface CreatePromptRunResponse {
    /**
     * Prompt run ID
     * @type {string}
     * @memberof CreatePromptRunResponse
     */
    id: string;
    /**
     * Thread ID for multi-turn runs
     * @type {string}
     * @memberof CreatePromptRunResponse
     */
    thread: string;
}

/**
 * Check if a given object implements the CreatePromptRunResponse interface.
 */
export function instanceOfCreatePromptRunResponse(value: object): value is CreatePromptRunResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('thread' in value) || value['thread'] === undefined) return false;
    return true;
}

export function CreatePromptRunResponseFromJSON(json: any): CreatePromptRunResponse {
    return CreatePromptRunResponseFromJSONTyped(json, false);
}

export function CreatePromptRunResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePromptRunResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'thread': json['thread'],
    };
}

export function CreatePromptRunResponseToJSON(json: any): CreatePromptRunResponse {
    return CreatePromptRunResponseToJSONTyped(json, false);
}

export function CreatePromptRunResponseToJSONTyped(value?: CreatePromptRunResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'thread': value['thread'],
    };
}

