/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateWorkflowRunMetadataValue } from './CreateWorkflowRunMetadataValue';
import {
    CreateWorkflowRunMetadataValueFromJSON,
    CreateWorkflowRunMetadataValueFromJSONTyped,
    CreateWorkflowRunMetadataValueToJSON,
    CreateWorkflowRunMetadataValueToJSONTyped,
} from './CreateWorkflowRunMetadataValue';

/**
 * Request payload for creating a prompt run.
 * @export
 * @interface CreatePromptRun
 */
export interface CreatePromptRun {
    /**
     * Key-value map of input variable names to their values.
     * @type {{ [key: string]: string; }}
     * @memberof CreatePromptRun
     */
    inputs: { [key: string]: string; };
    /**
     * Thread ID to continue a multi-turn conversation. Omit to start a new thread.
     * @type {string}
     * @memberof CreatePromptRun
     */
    thread?: string | null;
    /**
     * Processing priority.
     * @type {CreatePromptRunPriorityEnum}
     * @memberof CreatePromptRun
     */
    priority?: CreatePromptRunPriorityEnum;
    /**
     * Environment that scopes which webhooks fire and which environment variables the run can access. Uses the default environment when omitted.
     * @type {string}
     * @memberof CreatePromptRun
     */
    environment?: string | null;
    /**
     * Runtime environment variable overrides for this run. Keys must be UPPER_CASE. At most 50 entries, 64 KB total.
     * @type {{ [key: string]: string; }}
     * @memberof CreatePromptRun
     */
    envVars?: { [key: string]: string; };
    /**
     * Arbitrary key-value metadata attached to the run. Values can be strings or arrays of strings.
     * @type {{ [key: string]: CreateWorkflowRunMetadataValue; }}
     * @memberof CreatePromptRun
     */
    metadata?: { [key: string]: CreateWorkflowRunMetadataValue; };
    /**
     * Memory channel within the thread. Prompts on the same channel share conversational history; different channels are isolated.
     * @type {string}
     * @memberof CreatePromptRun
     */
    channel?: string;
}


/**
 * @export
 */
export const CreatePromptRunPriorityEnum = {
    Onsite: 'onsite',
    Normal: 'normal',
    Low: 'low'
} as const;
export type CreatePromptRunPriorityEnum = typeof CreatePromptRunPriorityEnum[keyof typeof CreatePromptRunPriorityEnum];


/**
 * Check if a given object implements the CreatePromptRun interface.
 */
export function instanceOfCreatePromptRun(value: object): value is CreatePromptRun {
    if (!('inputs' in value) || value['inputs'] === undefined) return false;
    return true;
}

export function CreatePromptRunFromJSON(json: any): CreatePromptRun {
    return CreatePromptRunFromJSONTyped(json, false);
}

export function CreatePromptRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePromptRun {
    if (json == null) {
        return json;
    }
    return {
        
        'inputs': json['inputs'],
        'thread': json['thread'] == null ? undefined : json['thread'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'environment': json['environment'] == null ? undefined : json['environment'],
        'envVars': json['envVars'] == null ? undefined : json['envVars'],
        'metadata': json['metadata'] == null ? undefined : (mapValues(json['metadata'], CreateWorkflowRunMetadataValueFromJSON)),
        'channel': json['channel'] == null ? undefined : json['channel'],
    };
}

export function CreatePromptRunToJSON(json: any): CreatePromptRun {
    return CreatePromptRunToJSONTyped(json, false);
}

export function CreatePromptRunToJSONTyped(value?: CreatePromptRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inputs': value['inputs'],
        'thread': value['thread'],
        'priority': value['priority'],
        'environment': value['environment'],
        'envVars': value['envVars'],
        'metadata': value['metadata'] == null ? undefined : (mapValues(value['metadata'], CreateWorkflowRunMetadataValueToJSON)),
        'channel': value['channel'],
    };
}

