/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateWorkflowRunMetadataValue } from './CreateWorkflowRunMetadataValue';
import {
    CreateWorkflowRunMetadataValueFromJSON,
    CreateWorkflowRunMetadataValueFromJSONTyped,
    CreateWorkflowRunMetadataValueToJSON,
    CreateWorkflowRunMetadataValueToJSONTyped,
} from './CreateWorkflowRunMetadataValue';

/**
 * Request payload for creating a workflow run.
 * @export
 * @interface CreateWorkflowRun
 */
export interface CreateWorkflowRun {
    /**
     * Key-value map of input variable names to their values.
     * @type {{ [key: string]: string; }}
     * @memberof CreateWorkflowRun
     */
    inputs: { [key: string]: string; };
    /**
     * Thread ID to continue a multi-turn conversation. Omit to start a new thread.
     * @type {string}
     * @memberof CreateWorkflowRun
     */
    thread?: string | null;
    /**
     * Processing priority.
     * @type {CreateWorkflowRunPriorityEnum}
     * @memberof CreateWorkflowRun
     */
    priority?: CreateWorkflowRunPriorityEnum;
    /**
     * Environment that scopes which webhooks fire and which environment variables the run can access. Uses the default environment when omitted.
     * @type {string}
     * @memberof CreateWorkflowRun
     */
    environment?: string | null;
    /**
     * Runtime environment variable overrides for this run. Keys must be UPPER_CASE. At most 50 entries, 64 KB total.
     * @type {{ [key: string]: string; }}
     * @memberof CreateWorkflowRun
     */
    envVars?: { [key: string]: string; };
    /**
     * Arbitrary key-value metadata attached to the run. Values can be strings or arrays of strings.
     * @type {{ [key: string]: CreateWorkflowRunMetadataValue; }}
     * @memberof CreateWorkflowRun
     */
    metadata?: { [key: string]: CreateWorkflowRunMetadataValue; };
}


/**
 * @export
 */
export const CreateWorkflowRunPriorityEnum = {
    Onsite: 'onsite',
    Normal: 'normal',
    Low: 'low'
} as const;
export type CreateWorkflowRunPriorityEnum = typeof CreateWorkflowRunPriorityEnum[keyof typeof CreateWorkflowRunPriorityEnum];


/**
 * Check if a given object implements the CreateWorkflowRun interface.
 */
export function instanceOfCreateWorkflowRun(value: object): value is CreateWorkflowRun {
    if (!('inputs' in value) || value['inputs'] === undefined) return false;
    return true;
}

export function CreateWorkflowRunFromJSON(json: any): CreateWorkflowRun {
    return CreateWorkflowRunFromJSONTyped(json, false);
}

export function CreateWorkflowRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkflowRun {
    if (json == null) {
        return json;
    }
    return {
        
        'inputs': json['inputs'],
        'thread': json['thread'] == null ? undefined : json['thread'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'environment': json['environment'] == null ? undefined : json['environment'],
        'envVars': json['envVars'] == null ? undefined : json['envVars'],
        'metadata': json['metadata'] == null ? undefined : (mapValues(json['metadata'], CreateWorkflowRunMetadataValueFromJSON)),
    };
}

export function CreateWorkflowRunToJSON(json: any): CreateWorkflowRun {
    return CreateWorkflowRunToJSONTyped(json, false);
}

export function CreateWorkflowRunToJSONTyped(value?: CreateWorkflowRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inputs': value['inputs'],
        'thread': value['thread'],
        'priority': value['priority'],
        'environment': value['environment'],
        'envVars': value['envVars'],
        'metadata': value['metadata'] == null ? undefined : (mapValues(value['metadata'], CreateWorkflowRunMetadataValueToJSON)),
    };
}

