/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One emit-tool call: the tool name and its schema-validated payload.
 * @export
 * @interface EmittedItem
 */
export interface EmittedItem {
    /**
     * The emit tool that produced this payload.
     * @type {string}
     * @memberof EmittedItem
     */
    tool: string;
    /**
     * The payload — the tool-call arguments, verbatim.
     * @type {object}
     * @memberof EmittedItem
     */
    payload: object;
}

/**
 * Check if a given object implements the EmittedItem interface.
 */
export function instanceOfEmittedItem(value: object): value is EmittedItem {
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function EmittedItemFromJSON(json: any): EmittedItem {
    return EmittedItemFromJSONTyped(json, false);
}

export function EmittedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmittedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'tool': json['tool'],
        'payload': json['payload'],
    };
}

export function EmittedItemToJSON(json: any): EmittedItem {
    return EmittedItemToJSONTyped(json, false);
}

export function EmittedItemToJSONTyped(value?: EmittedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tool': value['tool'],
        'payload': value['payload'],
    };
}

