/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Emit a schema-validated payload: the arguments are the result.
 * @export
 * @interface Emit
 */
export interface Emit {
    /**
     * JSON schema of the payload this tool emits.
     * @type {string}
     * @memberof Emit
     */
    paramsSchema: string;
    /**
     * The tool’s name.
     * @type {string}
     * @memberof Emit
     */
    name: string;
    /**
     * The tool’s description.
     * @type {string}
     * @memberof Emit
     */
    description?: string | null;
    /**
     * Whether to stop processing if a tool call fails.
     * @type {boolean}
     * @memberof Emit
     */
    failFast: boolean;
    /**
     * 
     * @type {EmitTypeEnum}
     * @memberof Emit
     */
    type: EmitTypeEnum;
}


/**
 * @export
 */
export const EmitTypeEnum = {
    Emit: 'emit'
} as const;
export type EmitTypeEnum = typeof EmitTypeEnum[keyof typeof EmitTypeEnum];


/**
 * Check if a given object implements the Emit interface.
 */
export function instanceOfEmit(value: object): value is Emit {
    if (!('paramsSchema' in value) || value['paramsSchema'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('failFast' in value) || value['failFast'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'emit') return false;
    
    return true;
}

export function EmitFromJSON(json: any): Emit {
    return EmitFromJSONTyped(json, false);
}

export function EmitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Emit {
    if (json == null) {
        return json;
    }
    return {
        
        'paramsSchema': json['paramsSchema'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'failFast': json['failFast'],
        'type': json['type'],
    };
}

export function EmitToJSON(json: any): Emit {
    return EmitToJSONTyped(json, false);
}

export function EmitToJSONTyped(value?: Emit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paramsSchema': value['paramsSchema'],
        'name': value['name'],
        'description': value['description'],
        'failFast': value['failFast'],
        'type': value['type'],
    };
}

