/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPromptRevisionVersionParameter
 */
export interface GetPromptRevisionVersionParameter {
}

/**
 * Check if a given object implements the GetPromptRevisionVersionParameter interface.
 */
export function instanceOfGetPromptRevisionVersionParameter(value: object): value is GetPromptRevisionVersionParameter {
    return true;
}

export function GetPromptRevisionVersionParameterFromJSON(json: any): GetPromptRevisionVersionParameter {
    return GetPromptRevisionVersionParameterFromJSONTyped(json, false);
}

export function GetPromptRevisionVersionParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPromptRevisionVersionParameter {
    return json;
}

export function GetPromptRevisionVersionParameterToJSON(json: any): GetPromptRevisionVersionParameter {
    return GetPromptRevisionVersionParameterToJSONTyped(json, false);
}

export function GetPromptRevisionVersionParameterToJSONTyped(value?: GetPromptRevisionVersionParameter | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

