/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpHeader
 */
export interface HttpHeader {
    /**
     * 
     * @type {string}
     * @memberof HttpHeader
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof HttpHeader
     */
    value: string;
}

/**
 * Check if a given object implements the HttpHeader interface.
 */
export function instanceOfHttpHeader(value: object): value is HttpHeader {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function HttpHeaderFromJSON(json: any): HttpHeader {
    return HttpHeaderFromJSONTyped(json, false);
}

export function HttpHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpHeader {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function HttpHeaderToJSON(json: any): HttpHeader {
    return HttpHeaderToJSONTyped(json, false);
}

export function HttpHeaderToJSONTyped(value?: HttpHeader | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

