/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpHeader } from './HttpHeader';
import {
    HttpHeaderFromJSON,
    HttpHeaderFromJSONTyped,
    HttpHeaderToJSON,
    HttpHeaderToJSONTyped,
} from './HttpHeader';

/**
 * External HTTP call tool.
 * @export
 * @interface HttpCall
 */
export interface HttpCall {
    /**
     * JSON schema of the parameters this tool expects.
     * @type {string}
     * @memberof HttpCall
     */
    paramsSchema: string;
    /**
     * The URL to call. Can contain ${ENV_VAR} and {{inputName}} placeholders.
     * @type {string}
     * @memberof HttpCall
     */
    url: string;
    /**
     * 
     * @type {HttpCallMethodEnum}
     * @memberof HttpCall
     */
    method: HttpCallMethodEnum;
    /**
     * The headers to send with the HTTP request. Can contain ${ENV_VAR} and {{inputName}} placeholders.
     * @type {Array<HttpHeader>}
     * @memberof HttpCall
     */
    headers?: Array<HttpHeader>;
    /**
     * The tool’s name.
     * @type {string}
     * @memberof HttpCall
     */
    name: string;
    /**
     * The tool’s description.
     * @type {string}
     * @memberof HttpCall
     */
    description?: string | null;
    /**
     * Whether to stop processing if a tool call fails.
     * @type {boolean}
     * @memberof HttpCall
     */
    failFast?: boolean;
    /**
     * 
     * @type {HttpCallTypeEnum}
     * @memberof HttpCall
     */
    type: HttpCallTypeEnum;
}


/**
 * @export
 */
export const HttpCallMethodEnum = {
    Get: 'GET',
    Post: 'POST',
    Put: 'PUT',
    Patch: 'PATCH',
    Delete: 'DELETE'
} as const;
export type HttpCallMethodEnum = typeof HttpCallMethodEnum[keyof typeof HttpCallMethodEnum];

/**
 * @export
 */
export const HttpCallTypeEnum = {
    Http: 'http'
} as const;
export type HttpCallTypeEnum = typeof HttpCallTypeEnum[keyof typeof HttpCallTypeEnum];


/**
 * Check if a given object implements the HttpCall interface.
 */
export function instanceOfHttpCall(value: object): value is HttpCall {
    if (!('paramsSchema' in value) || value['paramsSchema'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'http') return false;
    
    return true;
}

export function HttpCallFromJSON(json: any): HttpCall {
    return HttpCallFromJSONTyped(json, false);
}

export function HttpCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpCall {
    if (json == null) {
        return json;
    }
    return {
        
        'paramsSchema': json['paramsSchema'],
        'url': json['url'],
        'method': json['method'],
        'headers': json['headers'] == null ? undefined : ((json['headers'] as Array<any>).map(HttpHeaderFromJSON)),
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'failFast': json['failFast'] == null ? undefined : json['failFast'],
        'type': json['type'],
    };
}

export function HttpCallToJSON(json: any): HttpCall {
    return HttpCallToJSONTyped(json, false);
}

export function HttpCallToJSONTyped(value?: HttpCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paramsSchema': value['paramsSchema'],
        'url': value['url'],
        'method': value['method'],
        'headers': value['headers'] == null ? undefined : ((value['headers'] as Array<any>).map(HttpHeaderToJSON)),
        'name': value['name'],
        'description': value['description'],
        'failFast': value['failFast'],
        'type': value['type'],
    };
}

