/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * JSON object response format.
 * @export
 * @interface JsonObjectFormat
 */
export interface JsonObjectFormat {
    /**
     * 
     * @type {JsonObjectFormatTypeEnum}
     * @memberof JsonObjectFormat
     */
    type: JsonObjectFormatTypeEnum;
}


/**
 * @export
 */
export const JsonObjectFormatTypeEnum = {
    JsonObject: 'json_object'
} as const;
export type JsonObjectFormatTypeEnum = typeof JsonObjectFormatTypeEnum[keyof typeof JsonObjectFormatTypeEnum];


/**
 * Check if a given object implements the JsonObjectFormat interface.
 */
export function instanceOfJsonObjectFormat(value: object): value is JsonObjectFormat {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'json_object') return false;
    
    return true;
}

export function JsonObjectFormatFromJSON(json: any): JsonObjectFormat {
    return JsonObjectFormatFromJSONTyped(json, false);
}

export function JsonObjectFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonObjectFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function JsonObjectFormatToJSON(json: any): JsonObjectFormat {
    return JsonObjectFormatToJSONTyped(json, false);
}

export function JsonObjectFormatToJSONTyped(value?: JsonObjectFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

