/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * JSON schema response format.
 * @export
 * @interface JsonSchemaFormat
 */
export interface JsonSchemaFormat {
    /**
     * Schema name.
     * @type {string}
     * @memberof JsonSchemaFormat
     */
    name: string;
    /**
     * The JSON schema as string.
     * @type {string}
     * @memberof JsonSchemaFormat
     */
    schema: string;
    /**
     * Whether the model should follow the schema strictly.
     * @type {boolean}
     * @memberof JsonSchemaFormat
     */
    strict?: boolean | null;
    /**
     * Schema description.
     * @type {string}
     * @memberof JsonSchemaFormat
     */
    description?: string | null;
    /**
     * 
     * @type {JsonSchemaFormatTypeEnum}
     * @memberof JsonSchemaFormat
     */
    type: JsonSchemaFormatTypeEnum;
}


/**
 * @export
 */
export const JsonSchemaFormatTypeEnum = {
    JsonSchema: 'json_schema'
} as const;
export type JsonSchemaFormatTypeEnum = typeof JsonSchemaFormatTypeEnum[keyof typeof JsonSchemaFormatTypeEnum];


/**
 * Check if a given object implements the JsonSchemaFormat interface.
 */
export function instanceOfJsonSchemaFormat(value: object): value is JsonSchemaFormat {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('schema' in value) || value['schema'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'json_schema') return false;
    
    return true;
}

export function JsonSchemaFormatFromJSON(json: any): JsonSchemaFormat {
    return JsonSchemaFormatFromJSONTyped(json, false);
}

export function JsonSchemaFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonSchemaFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'schema': json['schema'],
        'strict': json['strict'] == null ? undefined : json['strict'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'],
    };
}

export function JsonSchemaFormatToJSON(json: any): JsonSchemaFormat {
    return JsonSchemaFormatToJSONTyped(json, false);
}

export function JsonSchemaFormatToJSONTyped(value?: JsonSchemaFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'schema': value['schema'],
        'strict': value['strict'],
        'description': value['description'],
        'type': value['type'],
    };
}

