/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KnowledgeDocumentStatus } from './KnowledgeDocumentStatus';
import {
    KnowledgeDocumentStatusFromJSON,
    KnowledgeDocumentStatusFromJSONTyped,
    KnowledgeDocumentStatusToJSON,
    KnowledgeDocumentStatusToJSONTyped,
} from './KnowledgeDocumentStatus';

/**
 * Knowledge document
 * @export
 * @interface KnowledgeDocumentResponse
 */
export interface KnowledgeDocumentResponse {
    /**
     * Document ID
     * @type {string}
     * @memberof KnowledgeDocumentResponse
     */
    id: string;
    /**
     * Processing status
     * @type {KnowledgeDocumentStatus}
     * @memberof KnowledgeDocumentResponse
     */
    status: KnowledgeDocumentStatus;
    /**
     * Original file name
     * @type {string}
     * @memberof KnowledgeDocumentResponse
     */
    fileName: string;
    /**
     * File size in bytes
     * @type {number}
     * @memberof KnowledgeDocumentResponse
     */
    bytes: number;
    /**
     * Number of chunks extracted
     * @type {number}
     * @memberof KnowledgeDocumentResponse
     */
    chunkCount: number;
}



/**
 * Check if a given object implements the KnowledgeDocumentResponse interface.
 */
export function instanceOfKnowledgeDocumentResponse(value: object): value is KnowledgeDocumentResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    if (!('chunkCount' in value) || value['chunkCount'] === undefined) return false;
    return true;
}

export function KnowledgeDocumentResponseFromJSON(json: any): KnowledgeDocumentResponse {
    return KnowledgeDocumentResponseFromJSONTyped(json, false);
}

export function KnowledgeDocumentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeDocumentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': KnowledgeDocumentStatusFromJSON(json['status']),
        'fileName': json['fileName'],
        'bytes': json['bytes'],
        'chunkCount': json['chunkCount'],
    };
}

export function KnowledgeDocumentResponseToJSON(json: any): KnowledgeDocumentResponse {
    return KnowledgeDocumentResponseToJSONTyped(json, false);
}

export function KnowledgeDocumentResponseToJSONTyped(value?: KnowledgeDocumentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': KnowledgeDocumentStatusToJSON(value['status']),
        'fileName': value['fileName'],
        'bytes': value['bytes'],
        'chunkCount': value['chunkCount'],
    };
}

