/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KnowledgeDocumentStatus } from './KnowledgeDocumentStatus';
import {
    KnowledgeDocumentStatusFromJSON,
    KnowledgeDocumentStatusFromJSONTyped,
    KnowledgeDocumentStatusToJSON,
    KnowledgeDocumentStatusToJSONTyped,
} from './KnowledgeDocumentStatus';

/**
 * Webhook payload for finished knowledge documents.
 * @export
 * @interface KnowledgeDocumentFinished
 */
export interface KnowledgeDocumentFinished {
    /**
     * Knowledge document ID
     * @type {string}
     * @memberof KnowledgeDocumentFinished
     */
    id: string;
    /**
     * Document processing status
     * @type {KnowledgeDocumentStatus}
     * @memberof KnowledgeDocumentFinished
     */
    status: KnowledgeDocumentStatus;
    /**
     * Number of chunks extracted
     * @type {number}
     * @memberof KnowledgeDocumentFinished
     */
    chunkCount: number;
}



/**
 * Check if a given object implements the KnowledgeDocumentFinished interface.
 */
export function instanceOfKnowledgeDocumentFinished(value: object): value is KnowledgeDocumentFinished {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('chunkCount' in value) || value['chunkCount'] === undefined) return false;
    return true;
}

export function KnowledgeDocumentFinishedFromJSON(json: any): KnowledgeDocumentFinished {
    return KnowledgeDocumentFinishedFromJSONTyped(json, false);
}

export function KnowledgeDocumentFinishedFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeDocumentFinished {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': KnowledgeDocumentStatusFromJSON(json['status']),
        'chunkCount': json['chunkCount'],
    };
}

export function KnowledgeDocumentFinishedToJSON(json: any): KnowledgeDocumentFinished {
    return KnowledgeDocumentFinishedToJSONTyped(json, false);
}

export function KnowledgeDocumentFinishedToJSONTyped(value?: KnowledgeDocumentFinished | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': KnowledgeDocumentStatusToJSON(value['status']),
        'chunkCount': value['chunkCount'],
    };
}

