/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const KnowledgeDocumentStatus = {
    Pending: 'pending',
    Sealed: 'sealed',
    Ready: 'ready',
    Failed: 'failed'
} as const;
export type KnowledgeDocumentStatus = typeof KnowledgeDocumentStatus[keyof typeof KnowledgeDocumentStatus];


export function instanceOfKnowledgeDocumentStatus(value: any): boolean {
    for (const key in KnowledgeDocumentStatus) {
        if (Object.prototype.hasOwnProperty.call(KnowledgeDocumentStatus, key)) {
            if (KnowledgeDocumentStatus[key as keyof typeof KnowledgeDocumentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function KnowledgeDocumentStatusFromJSON(json: any): KnowledgeDocumentStatus {
    return KnowledgeDocumentStatusFromJSONTyped(json, false);
}

export function KnowledgeDocumentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeDocumentStatus {
    return json as KnowledgeDocumentStatus;
}

export function KnowledgeDocumentStatusToJSON(value?: KnowledgeDocumentStatus | null): any {
    return value as any;
}

export function KnowledgeDocumentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): KnowledgeDocumentStatus {
    return value as KnowledgeDocumentStatus;
}

