/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const KnowledgeBaseStatus = {
    Pending: 'pending',
    Ready: 'ready',
    Failed: 'failed'
} as const;
export type KnowledgeBaseStatus = typeof KnowledgeBaseStatus[keyof typeof KnowledgeBaseStatus];


export function instanceOfKnowledgeBaseStatus(value: any): boolean {
    for (const key in KnowledgeBaseStatus) {
        if (Object.prototype.hasOwnProperty.call(KnowledgeBaseStatus, key)) {
            if (KnowledgeBaseStatus[key as keyof typeof KnowledgeBaseStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function KnowledgeBaseStatusFromJSON(json: any): KnowledgeBaseStatus {
    return KnowledgeBaseStatusFromJSONTyped(json, false);
}

export function KnowledgeBaseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeBaseStatus {
    return json as KnowledgeBaseStatus;
}

export function KnowledgeBaseStatusToJSON(value?: KnowledgeBaseStatus | null): any {
    return value as any;
}

export function KnowledgeBaseStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): KnowledgeBaseStatus {
    return value as KnowledgeBaseStatus;
}

