/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KnowledgeBaseStatus } from './KnowledgeBaseStatus';
import {
    KnowledgeBaseStatusFromJSON,
    KnowledgeBaseStatusFromJSONTyped,
    KnowledgeBaseStatusToJSON,
    KnowledgeBaseStatusToJSONTyped,
} from './KnowledgeBaseStatus';

/**
 * Webhook payload for finished knowledge bases.
 * @export
 * @interface KnowledgeBaseFinished
 */
export interface KnowledgeBaseFinished {
    /**
     * Knowledge base ID
     * @type {string}
     * @memberof KnowledgeBaseFinished
     */
    id: string;
    /**
     * Knowledge base status
     * @type {KnowledgeBaseStatus}
     * @memberof KnowledgeBaseFinished
     */
    status: KnowledgeBaseStatus;
    /**
     * Total document count
     * @type {number}
     * @memberof KnowledgeBaseFinished
     */
    documentCount: number;
    /**
     * Total chunk count
     * @type {number}
     * @memberof KnowledgeBaseFinished
     */
    chunkCount: number;
}



/**
 * Check if a given object implements the KnowledgeBaseFinished interface.
 */
export function instanceOfKnowledgeBaseFinished(value: object): value is KnowledgeBaseFinished {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('documentCount' in value) || value['documentCount'] === undefined) return false;
    if (!('chunkCount' in value) || value['chunkCount'] === undefined) return false;
    return true;
}

export function KnowledgeBaseFinishedFromJSON(json: any): KnowledgeBaseFinished {
    return KnowledgeBaseFinishedFromJSONTyped(json, false);
}

export function KnowledgeBaseFinishedFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeBaseFinished {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': KnowledgeBaseStatusFromJSON(json['status']),
        'documentCount': json['documentCount'],
        'chunkCount': json['chunkCount'],
    };
}

export function KnowledgeBaseFinishedToJSON(json: any): KnowledgeBaseFinished {
    return KnowledgeBaseFinishedToJSONTyped(json, false);
}

export function KnowledgeBaseFinishedToJSONTyped(value?: KnowledgeBaseFinished | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': KnowledgeBaseStatusToJSON(value['status']),
        'documentCount': value['documentCount'],
        'chunkCount': value['chunkCount'],
    };
}

