/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * RAG tool to search knowledge base.
 * @export
 * @interface KnowledgeSearch
 */
export interface KnowledgeSearch {
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSearch
     */
    knowledgeBaseId: string;
    /**
     * The tool’s name.
     * @type {string}
     * @memberof KnowledgeSearch
     */
    name: string;
    /**
     * The tool’s description.
     * @type {string}
     * @memberof KnowledgeSearch
     */
    description?: string | null;
    /**
     * Whether to stop processing if a tool call fails.
     * @type {boolean}
     * @memberof KnowledgeSearch
     */
    failFast?: boolean;
    /**
     * 
     * @type {KnowledgeSearchTypeEnum}
     * @memberof KnowledgeSearch
     */
    type: KnowledgeSearchTypeEnum;
}


/**
 * @export
 */
export const KnowledgeSearchTypeEnum = {
    KnowledgeSearch: 'knowledge_search'
} as const;
export type KnowledgeSearchTypeEnum = typeof KnowledgeSearchTypeEnum[keyof typeof KnowledgeSearchTypeEnum];


/**
 * Check if a given object implements the KnowledgeSearch interface.
 */
export function instanceOfKnowledgeSearch(value: object): value is KnowledgeSearch {
    if (!('knowledgeBaseId' in value) || value['knowledgeBaseId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'knowledge_search') return false;
    
    return true;
}

export function KnowledgeSearchFromJSON(json: any): KnowledgeSearch {
    return KnowledgeSearchFromJSONTyped(json, false);
}

export function KnowledgeSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeSearch {
    if (json == null) {
        return json;
    }
    return {
        
        'knowledgeBaseId': json['knowledgeBaseId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'failFast': json['failFast'] == null ? undefined : json['failFast'],
        'type': json['type'],
    };
}

export function KnowledgeSearchToJSON(json: any): KnowledgeSearch {
    return KnowledgeSearchToJSONTyped(json, false);
}

export function KnowledgeSearchToJSONTyped(value?: KnowledgeSearch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'knowledgeBaseId': value['knowledgeBaseId'],
        'name': value['name'],
        'description': value['description'],
        'failFast': value['failFast'],
        'type': value['type'],
    };
}

