/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KnowledgeDocumentStatus } from './KnowledgeDocumentStatus';
import {
    KnowledgeDocumentStatusFromJSON,
    KnowledgeDocumentStatusFromJSONTyped,
    KnowledgeDocumentStatusToJSON,
    KnowledgeDocumentStatusToJSONTyped,
} from './KnowledgeDocumentStatus';

/**
 * Knowledge document summary (without counts)
 * @export
 * @interface KnowledgeDocumentSummary
 */
export interface KnowledgeDocumentSummary {
    /**
     * Document ID
     * @type {string}
     * @memberof KnowledgeDocumentSummary
     */
    id: string;
    /**
     * Processing status
     * @type {KnowledgeDocumentStatus}
     * @memberof KnowledgeDocumentSummary
     */
    status: KnowledgeDocumentStatus;
    /**
     * Original file name
     * @type {string}
     * @memberof KnowledgeDocumentSummary
     */
    fileName: string;
    /**
     * File size in bytes
     * @type {number}
     * @memberof KnowledgeDocumentSummary
     */
    bytes: number;
    /**
     * MIME type
     * @type {string}
     * @memberof KnowledgeDocumentSummary
     */
    mimeType: string;
}



/**
 * Check if a given object implements the KnowledgeDocumentSummary interface.
 */
export function instanceOfKnowledgeDocumentSummary(value: object): value is KnowledgeDocumentSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    return true;
}

export function KnowledgeDocumentSummaryFromJSON(json: any): KnowledgeDocumentSummary {
    return KnowledgeDocumentSummaryFromJSONTyped(json, false);
}

export function KnowledgeDocumentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeDocumentSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': KnowledgeDocumentStatusFromJSON(json['status']),
        'fileName': json['fileName'],
        'bytes': json['bytes'],
        'mimeType': json['mimeType'],
    };
}

export function KnowledgeDocumentSummaryToJSON(json: any): KnowledgeDocumentSummary {
    return KnowledgeDocumentSummaryToJSONTyped(json, false);
}

export function KnowledgeDocumentSummaryToJSONTyped(value?: KnowledgeDocumentSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': KnowledgeDocumentStatusToJSON(value['status']),
        'fileName': value['fileName'],
        'bytes': value['bytes'],
        'mimeType': value['mimeType'],
    };
}

