/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KnowledgeBaseStatus } from './KnowledgeBaseStatus';
import {
    KnowledgeBaseStatusFromJSON,
    KnowledgeBaseStatusFromJSONTyped,
    KnowledgeBaseStatusToJSON,
    KnowledgeBaseStatusToJSONTyped,
} from './KnowledgeBaseStatus';
import type { KnowledgeDocumentSummary } from './KnowledgeDocumentSummary';
import {
    KnowledgeDocumentSummaryFromJSON,
    KnowledgeDocumentSummaryFromJSONTyped,
    KnowledgeDocumentSummaryToJSON,
    KnowledgeDocumentSummaryToJSONTyped,
} from './KnowledgeDocumentSummary';

/**
 * Knowledge base with documents
 * @export
 * @interface KnowledgeBaseResponse
 */
export interface KnowledgeBaseResponse {
    /**
     * Knowledge base ID
     * @type {string}
     * @memberof KnowledgeBaseResponse
     */
    id: string;
    /**
     * Processing status
     * @type {KnowledgeBaseStatus}
     * @memberof KnowledgeBaseResponse
     */
    status: KnowledgeBaseStatus;
    /**
     * Total number of documents
     * @type {number}
     * @memberof KnowledgeBaseResponse
     */
    documentCount: number;
    /**
     * Total number of chunks across all documents
     * @type {number}
     * @memberof KnowledgeBaseResponse
     */
    chunkCount: number;
    /**
     * 
     * @type {Array<KnowledgeDocumentSummary>}
     * @memberof KnowledgeBaseResponse
     */
    documents: Array<KnowledgeDocumentSummary>;
}



/**
 * Check if a given object implements the KnowledgeBaseResponse interface.
 */
export function instanceOfKnowledgeBaseResponse(value: object): value is KnowledgeBaseResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('documentCount' in value) || value['documentCount'] === undefined) return false;
    if (!('chunkCount' in value) || value['chunkCount'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function KnowledgeBaseResponseFromJSON(json: any): KnowledgeBaseResponse {
    return KnowledgeBaseResponseFromJSONTyped(json, false);
}

export function KnowledgeBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': KnowledgeBaseStatusFromJSON(json['status']),
        'documentCount': json['documentCount'],
        'chunkCount': json['chunkCount'],
        'documents': ((json['documents'] as Array<any>).map(KnowledgeDocumentSummaryFromJSON)),
    };
}

export function KnowledgeBaseResponseToJSON(json: any): KnowledgeBaseResponse {
    return KnowledgeBaseResponseToJSONTyped(json, false);
}

export function KnowledgeBaseResponseToJSONTyped(value?: KnowledgeBaseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': KnowledgeBaseStatusToJSON(value['status']),
        'documentCount': value['documentCount'],
        'chunkCount': value['chunkCount'],
        'documents': ((value['documents'] as Array<any>).map(KnowledgeDocumentSummaryToJSON)),
    };
}

