/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Built-in MCP server tool.
 * @export
 * @interface Mcp
 */
export interface Mcp {
    /**
     * The MCP server tool’s name.
     * @type {string}
     * @memberof Mcp
     */
    name: string;
    /**
     * The URL of the MCP server.
     * @type {string}
     * @memberof Mcp
     */
    url: string;
    /**
     * Authorization token for the MCP server.
     * @type {string}
     * @memberof Mcp
     */
    authorizationToken?: string | null;
    /**
     * Tool names the model may call. Empty or omitted allows all of the server’s tools.
     * @type {Array<string>}
     * @memberof Mcp
     */
    allowedTools?: Array<string> | null;
    /**
     * 
     * @type {McpTypeEnum}
     * @memberof Mcp
     */
    type: McpTypeEnum;
}


/**
 * @export
 */
export const McpTypeEnum = {
    Mcp: 'mcp'
} as const;
export type McpTypeEnum = typeof McpTypeEnum[keyof typeof McpTypeEnum];


/**
 * Check if a given object implements the Mcp interface.
 */
export function instanceOfMcp(value: object): value is Mcp {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'mcp') return false;
    
    return true;
}

export function McpFromJSON(json: any): Mcp {
    return McpFromJSONTyped(json, false);
}

export function McpFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mcp {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'authorizationToken': json['authorizationToken'] == null ? undefined : json['authorizationToken'],
        'allowedTools': json['allowedTools'] == null ? undefined : json['allowedTools'],
        'type': json['type'],
    };
}

export function McpToJSON(json: any): Mcp {
    return McpToJSONTyped(json, false);
}

export function McpToJSONTyped(value?: Mcp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'authorizationToken': value['authorizationToken'],
        'allowedTools': value['allowedTools'],
        'type': value['type'],
    };
}

