/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Memory = {
    Stateless: 'stateless',
    ReadOnly: 'read_only',
    ReadWrite: 'read_write',
    WriteOnly: 'write_only'
} as const;
export type Memory = typeof Memory[keyof typeof Memory];


export function instanceOfMemory(value: any): boolean {
    for (const key in Memory) {
        if (Object.prototype.hasOwnProperty.call(Memory, key)) {
            if (Memory[key as keyof typeof Memory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MemoryFromJSON(json: any): Memory {
    return MemoryFromJSONTyped(json, false);
}

export function MemoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Memory {
    return json as Memory;
}

export function MemoryToJSON(value?: Memory | null): any {
    return value as any;
}

export function MemoryToJSONTyped(value: any, ignoreDiscriminator: boolean): Memory {
    return value as Memory;
}

