/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelCost
 */
export interface ModelCost {
    /**
     * 
     * @type {number}
     * @memberof ModelCost
     */
    input: number;
    /**
     * 
     * @type {number}
     * @memberof ModelCost
     */
    cachedInput?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ModelCost
     */
    output: number;
    /**
     * 
     * @type {number}
     * @memberof ModelCost
     */
    webSearch?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelCost
     */
    total: number;
}

/**
 * Check if a given object implements the ModelCost interface.
 */
export function instanceOfModelCost(value: object): value is ModelCost {
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ModelCostFromJSON(json: any): ModelCost {
    return ModelCostFromJSONTyped(json, false);
}

export function ModelCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelCost {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'],
        'cachedInput': json['cachedInput'] == null ? undefined : json['cachedInput'],
        'output': json['output'],
        'webSearch': json['webSearch'] == null ? undefined : json['webSearch'],
        'total': json['total'],
    };
}

export function ModelCostToJSON(json: any): ModelCost {
    return ModelCostToJSONTyped(json, false);
}

export function ModelCostToJSONTyped(value?: ModelCost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input': value['input'],
        'cachedInput': value['cachedInput'],
        'output': value['output'],
        'webSearch': value['webSearch'],
        'total': value['total'],
    };
}

