/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceTier } from './ServiceTier';
import {
    ServiceTierFromJSON,
    ServiceTierFromJSONTyped,
    ServiceTierToJSON,
    ServiceTierToJSONTyped,
} from './ServiceTier';

/**
 * AI model parameters.
 * @export
 * @interface ModelParams
 */
export interface ModelParams {
    /**
     * Maximum completion tokens.
     * @type {number}
     * @memberof ModelParams
     */
    maxCompletionTokens?: number | null;
    /**
     * Temperature.
     * @type {number}
     * @memberof ModelParams
     */
    temperature?: number | null;
    /**
     * Top P.
     * @type {number}
     * @memberof ModelParams
     */
    topP?: number | null;
    /**
     * Verbosity.
     * @type {ModelParamsVerbosityEnum}
     * @memberof ModelParams
     */
    verbosity?: ModelParamsVerbosityEnum | null;
    /**
     * Reasoning effort.
     * @type {ModelParamsReasoningEffortEnum}
     * @memberof ModelParams
     */
    reasoningEffort?: ModelParamsReasoningEffortEnum | null;
    /**
     * Return reasoning summary.
     * @type {boolean}
     * @memberof ModelParams
     */
    reasoningSummary?: boolean | null;
    /**
     * Service tier.
     * @type {ServiceTier}
     * @memberof ModelParams
     */
    serviceTier?: ServiceTier | null;
}


/**
 * @export
 */
export const ModelParamsVerbosityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type ModelParamsVerbosityEnum = typeof ModelParamsVerbosityEnum[keyof typeof ModelParamsVerbosityEnum];

/**
 * @export
 */
export const ModelParamsReasoningEffortEnum = {
    None: 'none',
    Minimal: 'minimal',
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Xhigh: 'xhigh',
    Max: 'max'
} as const;
export type ModelParamsReasoningEffortEnum = typeof ModelParamsReasoningEffortEnum[keyof typeof ModelParamsReasoningEffortEnum];


/**
 * Check if a given object implements the ModelParams interface.
 */
export function instanceOfModelParams(value: object): value is ModelParams {
    return true;
}

export function ModelParamsFromJSON(json: any): ModelParams {
    return ModelParamsFromJSONTyped(json, false);
}

export function ModelParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelParams {
    if (json == null) {
        return json;
    }
    return {
        
        'maxCompletionTokens': json['maxCompletionTokens'] == null ? undefined : json['maxCompletionTokens'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'topP': json['topP'] == null ? undefined : json['topP'],
        'verbosity': json['verbosity'] == null ? undefined : json['verbosity'],
        'reasoningEffort': json['reasoningEffort'] == null ? undefined : json['reasoningEffort'],
        'reasoningSummary': json['reasoningSummary'] == null ? undefined : json['reasoningSummary'],
        'serviceTier': json['serviceTier'] == null ? undefined : ServiceTierFromJSON(json['serviceTier']),
    };
}

export function ModelParamsToJSON(json: any): ModelParams {
    return ModelParamsToJSONTyped(json, false);
}

export function ModelParamsToJSONTyped(value?: ModelParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maxCompletionTokens': value['maxCompletionTokens'],
        'temperature': value['temperature'],
        'topP': value['topP'],
        'verbosity': value['verbosity'],
        'reasoningEffort': value['reasoningEffort'],
        'reasoningSummary': value['reasoningSummary'],
        'serviceTier': ServiceTierToJSON(value['serviceTier']),
    };
}

