/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Model = {
    Gpt55: 'gpt-5.5',
    Gpt55Pro: 'gpt-5.5-pro',
    Gpt54: 'gpt-5.4',
    Gpt54Mini: 'gpt-5.4-mini',
    Gpt54Nano: 'gpt-5.4-nano',
    Gpt54Pro: 'gpt-5.4-pro',
    Gpt52: 'gpt-5.2',
    Gpt52Pro: 'gpt-5.2-pro',
    Gpt51: 'gpt-5.1',
    Gpt41: 'gpt-4.1',
    Gpt41Mini: 'gpt-4.1-mini',
    O1Mini: 'o1-mini',
    Gpt4o: 'gpt-4o',
    Gpt4oMini: 'gpt-4o-mini',
    Gemini31ProPreview: 'gemini-3.1-pro-preview',
    Gemini3FlashPreview: 'gemini-3-flash-preview',
    Gemini25Pro: 'gemini-2.5-pro',
    Gemini25Flash: 'gemini-2.5-flash',
    Gemini25FlashLite: 'gemini-2.5-flash-lite',
    Gemini20Flash: 'gemini-2.0-flash',
    Gemini20FlashLite: 'gemini-2.0-flash-lite',
    ClaudeOpus48: 'claude-opus-4-8',
    ClaudeOpus47: 'claude-opus-4-7',
    ClaudeOpus46: 'claude-opus-4-6',
    ClaudeOpus45: 'claude-opus-4-5',
    ClaudeSonnet46: 'claude-sonnet-4-6',
    ClaudeSonnet45: 'claude-sonnet-4-5',
    ClaudeHaiku45: 'claude-haiku-4-5'
} as const;
export type Model = typeof Model[keyof typeof Model];


export function instanceOfModel(value: any): boolean {
    for (const key in Model) {
        if (Object.prototype.hasOwnProperty.call(Model, key)) {
            if (Model[key as keyof typeof Model] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ModelFromJSON(json: any): Model {
    return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
    return json as Model;
}

export function ModelToJSON(value?: Model | null): any {
    return value as any;
}

export function ModelToJSONTyped(value: any, ignoreDiscriminator: boolean): Model {
    return value as Model;
}

