/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunStatus } from './RunStatus';
import {
    RunStatusFromJSON,
    RunStatusFromJSONTyped,
    RunStatusToJSON,
    RunStatusToJSONTyped,
} from './RunStatus';

/**
 * Webhook payload for finished prompt runs.
 * @export
 * @interface PromptRunFinished
 */
export interface PromptRunFinished {
    /**
     * Prompt run ID
     * @type {string}
     * @memberof PromptRunFinished
     */
    id: string;
    /**
     * Prompt run status
     * @type {RunStatus}
     * @memberof PromptRunFinished
     */
    status: RunStatus;
}



/**
 * Check if a given object implements the PromptRunFinished interface.
 */
export function instanceOfPromptRunFinished(value: object): value is PromptRunFinished {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PromptRunFinishedFromJSON(json: any): PromptRunFinished {
    return PromptRunFinishedFromJSONTyped(json, false);
}

export function PromptRunFinishedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptRunFinished {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': RunStatusFromJSON(json['status']),
    };
}

export function PromptRunFinishedToJSON(json: any): PromptRunFinished {
    return PromptRunFinishedToJSONTyped(json, false);
}

export function PromptRunFinishedToJSONTyped(value?: PromptRunFinished | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': RunStatusToJSON(value['status']),
    };
}

