/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseFormat } from './ResponseFormat';
import {
    ResponseFormatFromJSON,
    ResponseFormatFromJSONTyped,
    ResponseFormatToJSON,
    ResponseFormatToJSONTyped,
} from './ResponseFormat';
import type { Memory } from './Memory';
import {
    MemoryFromJSON,
    MemoryFromJSONTyped,
    MemoryToJSON,
    MemoryToJSONTyped,
} from './Memory';
import type { Model } from './Model';
import {
    ModelFromJSON,
    ModelFromJSONTyped,
    ModelToJSON,
    ModelToJSONTyped,
} from './Model';
import type { ModelParams } from './ModelParams';
import {
    ModelParamsFromJSON,
    ModelParamsFromJSONTyped,
    ModelParamsToJSON,
    ModelParamsToJSONTyped,
} from './ModelParams';
import type { ContentMessageResponse } from './ContentMessageResponse';
import {
    ContentMessageResponseFromJSON,
    ContentMessageResponseFromJSONTyped,
    ContentMessageResponseToJSON,
    ContentMessageResponseToJSONTyped,
} from './ContentMessageResponse';
import type { Provider } from './Provider';
import {
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
    ProviderToJSONTyped,
} from './Provider';
import type { Tool } from './Tool';
import {
    ToolFromJSON,
    ToolFromJSONTyped,
    ToolToJSON,
    ToolToJSONTyped,
} from './Tool';

/**
 * Prompt revision
 * @export
 * @interface PromptRevision
 */
export interface PromptRevision {
    /**
     * Prompt revision ID.
     * @type {string}
     * @memberof PromptRevision
     */
    id: string;
    /**
     * Prompt ID.
     * @type {string}
     * @memberof PromptRevision
     */
    promptId: string;
    /**
     * Memory mode.
     * @type {Memory}
     * @memberof PromptRevision
     */
    memory: Memory;
    /**
     * AI provider.
     * @type {Provider}
     * @memberof PromptRevision
     */
    provider: Provider;
    /**
     * AI model.
     * @type {Model}
     * @memberof PromptRevision
     */
    model: Model;
    /**
     * Model parameters.
     * @type {ModelParams}
     * @memberof PromptRevision
     */
    modelParams: ModelParams;
    /**
     * AI model response format.
     * @type {ResponseFormat}
     * @memberof PromptRevision
     */
    responseFormat: ResponseFormat;
    /**
     * The system prompt.
     * @type {string}
     * @memberof PromptRevision
     */
    systemInstruction?: string | null;
    /**
     * User and assistant messages.
     * @type {Array<ContentMessageResponse>}
     * @memberof PromptRevision
     */
    messages: Array<ContentMessageResponse>;
    /**
     * Available tools.
     * @type {Array<Tool>}
     * @memberof PromptRevision
     */
    tools: Array<Tool>;
}



/**
 * Check if a given object implements the PromptRevision interface.
 */
export function instanceOfPromptRevision(value: object): value is PromptRevision {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('promptId' in value) || value['promptId'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('modelParams' in value) || value['modelParams'] === undefined) return false;
    if (!('responseFormat' in value) || value['responseFormat'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    if (!('tools' in value) || value['tools'] === undefined) return false;
    return true;
}

export function PromptRevisionFromJSON(json: any): PromptRevision {
    return PromptRevisionFromJSONTyped(json, false);
}

export function PromptRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'promptId': json['promptId'],
        'memory': MemoryFromJSON(json['memory']),
        'provider': ProviderFromJSON(json['provider']),
        'model': ModelFromJSON(json['model']),
        'modelParams': ModelParamsFromJSON(json['modelParams']),
        'responseFormat': ResponseFormatFromJSON(json['responseFormat']),
        'systemInstruction': json['systemInstruction'] == null ? undefined : json['systemInstruction'],
        'messages': ((json['messages'] as Array<any>).map(ContentMessageResponseFromJSON)),
        'tools': ((json['tools'] as Array<any>).map(ToolFromJSON)),
    };
}

export function PromptRevisionToJSON(json: any): PromptRevision {
    return PromptRevisionToJSONTyped(json, false);
}

export function PromptRevisionToJSONTyped(value?: PromptRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'promptId': value['promptId'],
        'memory': MemoryToJSON(value['memory']),
        'provider': ProviderToJSON(value['provider']),
        'model': ModelToJSON(value['model']),
        'modelParams': ModelParamsToJSON(value['modelParams']),
        'responseFormat': ResponseFormatToJSON(value['responseFormat']),
        'systemInstruction': value['systemInstruction'],
        'messages': ((value['messages'] as Array<any>).map(ContentMessageResponseToJSON)),
        'tools': ((value['tools'] as Array<any>).map(ToolToJSON)),
    };
}

