/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionRef } from './VersionRef';
import {
    VersionRefFromJSON,
    VersionRefFromJSONTyped,
    VersionRefToJSON,
    VersionRefToJSONTyped,
} from './VersionRef';

/**
 * Tool to invoke another prompt.
 * @export
 * @interface PromptCall
 */
export interface PromptCall {
    /**
     * Referencing the prompt revision either by id or version number or tag.
     * @type {VersionRef}
     * @memberof PromptCall
     */
    versionRef: VersionRef;
    /**
     * The tool’s name.
     * @type {string}
     * @memberof PromptCall
     */
    name: string;
    /**
     * The tool’s description.
     * @type {string}
     * @memberof PromptCall
     */
    description?: string | null;
    /**
     * Whether to stop processing if a tool call fails.
     * @type {boolean}
     * @memberof PromptCall
     */
    failFast?: boolean;
    /**
     * 
     * @type {PromptCallTypeEnum}
     * @memberof PromptCall
     */
    type: PromptCallTypeEnum;
}


/**
 * @export
 */
export const PromptCallTypeEnum = {
    Prompt: 'prompt'
} as const;
export type PromptCallTypeEnum = typeof PromptCallTypeEnum[keyof typeof PromptCallTypeEnum];


/**
 * Check if a given object implements the PromptCall interface.
 */
export function instanceOfPromptCall(value: object): value is PromptCall {
    if (!('versionRef' in value) || value['versionRef'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'prompt') return false;
    
    return true;
}

export function PromptCallFromJSON(json: any): PromptCall {
    return PromptCallFromJSONTyped(json, false);
}

export function PromptCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptCall {
    if (json == null) {
        return json;
    }
    return {
        
        'versionRef': VersionRefFromJSON(json['versionRef']),
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'failFast': json['failFast'] == null ? undefined : json['failFast'],
        'type': json['type'],
    };
}

export function PromptCallToJSON(json: any): PromptCall {
    return PromptCallToJSONTyped(json, false);
}

export function PromptCallToJSONTyped(value?: PromptCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'versionRef': VersionRefToJSON(value['versionRef']),
        'name': value['name'],
        'description': value['description'],
        'failFast': value['failFast'],
        'type': value['type'],
    };
}

