/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunStatus } from './RunStatus';
import {
    RunStatusFromJSON,
    RunStatusFromJSONTyped,
    RunStatusToJSON,
    RunStatusToJSONTyped,
} from './RunStatus';

/**
 * Prompt run status and result.
 * @export
 * @interface PromptRun
 */
export interface PromptRun {
    /**
     * Prompt run ID.
     * @type {string}
     * @memberof PromptRun
     */
    id: string;
    /**
     * Current run status.
     * @type {RunStatus}
     * @memberof PromptRun
     */
    status: RunStatus;
    /**
     * Timestamp when the run was created.
     * @type {Date}
     * @memberof PromptRun
     */
    createdAt: Date;
    /**
     * Timestamp when the run finished. Null while the run is pending.
     * @type {Date}
     * @memberof PromptRun
     */
    finishedAt?: Date | null;
    /**
     * LLM output text. Null while pending or when the run failed.
     * @type {string}
     * @memberof PromptRun
     */
    output?: string | null;
    /**
     * Error message if the run failed. Null on success.
     * @type {string}
     * @memberof PromptRun
     */
    error?: string | null;
}



/**
 * Check if a given object implements the PromptRun interface.
 */
export function instanceOfPromptRun(value: object): value is PromptRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PromptRunFromJSON(json: any): PromptRun {
    return PromptRunFromJSONTyped(json, false);
}

export function PromptRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': RunStatusFromJSON(json['status']),
        'createdAt': (new Date(json['createdAt'])),
        'finishedAt': json['finishedAt'] == null ? undefined : (new Date(json['finishedAt'])),
        'output': json['output'] == null ? undefined : json['output'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function PromptRunToJSON(json: any): PromptRun {
    return PromptRunToJSONTyped(json, false);
}

export function PromptRunToJSONTyped(value?: PromptRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': RunStatusToJSON(value['status']),
        'createdAt': value['createdAt'].toISOString(),
        'finishedAt': value['finishedAt'] == null ? value['finishedAt'] : value['finishedAt'].toISOString(),
        'output': value['output'],
        'error': value['error'],
    };
}

