/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmittedItem } from './EmittedItem';
import {
    EmittedItemFromJSON,
    EmittedItemFromJSONTyped,
    EmittedItemToJSON,
    EmittedItemToJSONTyped,
} from './EmittedItem';
import type { RunStatus } from './RunStatus';
import {
    RunStatusFromJSON,
    RunStatusFromJSONTyped,
    RunStatusToJSON,
    RunStatusToJSONTyped,
} from './RunStatus';
import type { TokenUsage } from './TokenUsage';
import {
    TokenUsageFromJSON,
    TokenUsageFromJSONTyped,
    TokenUsageToJSON,
    TokenUsageToJSONTyped,
} from './TokenUsage';
import type { TranscriptItem } from './TranscriptItem';
import {
    TranscriptItemFromJSON,
    TranscriptItemFromJSONTyped,
    TranscriptItemToJSON,
    TranscriptItemToJSONTyped,
} from './TranscriptItem';
import type { RunCost } from './RunCost';
import {
    RunCostFromJSON,
    RunCostFromJSONTyped,
    RunCostToJSON,
    RunCostToJSONTyped,
} from './RunCost';

/**
 * Prompt run status and result.
 * @export
 * @interface PromptRun
 */
export interface PromptRun {
    /**
     * Prompt run ID.
     * @type {string}
     * @memberof PromptRun
     */
    id: string;
    /**
     * Current run status.
     * @type {RunStatus}
     * @memberof PromptRun
     */
    status: RunStatus;
    /**
     * Timestamp when the run was created.
     * @type {Date}
     * @memberof PromptRun
     */
    createdAt: Date;
    /**
     * Timestamp when the run finished. Null while the run is pending.
     * @type {Date}
     * @memberof PromptRun
     */
    finishedAt?: Date | null;
    /**
     * LLM output text produced so far; read `status` for completeness. Null when the run failed, or when the model returned no text — e.g. a turn that was only tool calls or only reasoning.
     * @type {string}
     * @memberof PromptRun
     */
    output?: string | null;
    /**
     * Payloads produced by emit tools during this run, in call order. Empty until the run completes.
     * @type {Array<EmittedItem>}
     * @memberof PromptRun
     */
    emitted: Array<EmittedItem>;
    /**
     * The run as a renderable sequence: assistant text, the tools it used, and emit payloads in position. Empty until the run completes. `output` remains the flat text for callers that only need the answer.
     * @type {Array<TranscriptItem>}
     * @memberof PromptRun
     */
    transcript: Array<TranscriptItem>;
    /**
     * Error message from the latest failed attempt, kept even once a retry recovers — so a pending or completed run can carry one. Read `status` for the outcome.
     * @type {string}
     * @memberof PromptRun
     */
    error?: string | null;
    /**
     * Token usage accumulated over successful turns — a run that failed later still reports the earlier ones. Null until the first turn succeeds.
     * @type {TokenUsage}
     * @memberof PromptRun
     */
    tokenUsage?: TokenUsage | null;
    /**
     * Cost breakdown for the run. Null while pending, or when no published rate covers the run.
     * @type {RunCost}
     * @memberof PromptRun
     */
    cost?: RunCost | null;
}



/**
 * Check if a given object implements the PromptRun interface.
 */
export function instanceOfPromptRun(value: object): value is PromptRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('emitted' in value) || value['emitted'] === undefined) return false;
    if (!('transcript' in value) || value['transcript'] === undefined) return false;
    return true;
}

export function PromptRunFromJSON(json: any): PromptRun {
    return PromptRunFromJSONTyped(json, false);
}

export function PromptRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': RunStatusFromJSON(json['status']),
        'createdAt': (new Date(json['createdAt'])),
        'finishedAt': json['finishedAt'] == null ? undefined : (new Date(json['finishedAt'])),
        'output': json['output'] == null ? undefined : json['output'],
        'emitted': ((json['emitted'] as Array<any>).map(EmittedItemFromJSON)),
        'transcript': ((json['transcript'] as Array<any>).map(TranscriptItemFromJSON)),
        'error': json['error'] == null ? undefined : json['error'],
        'tokenUsage': json['tokenUsage'] == null ? undefined : TokenUsageFromJSON(json['tokenUsage']),
        'cost': json['cost'] == null ? undefined : RunCostFromJSON(json['cost']),
    };
}

export function PromptRunToJSON(json: any): PromptRun {
    return PromptRunToJSONTyped(json, false);
}

export function PromptRunToJSONTyped(value?: PromptRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': RunStatusToJSON(value['status']),
        'createdAt': value['createdAt'].toISOString(),
        'finishedAt': value['finishedAt'] == null ? value['finishedAt'] : value['finishedAt'].toISOString(),
        'output': value['output'],
        'emitted': ((value['emitted'] as Array<any>).map(EmittedItemToJSON)),
        'transcript': ((value['transcript'] as Array<any>).map(TranscriptItemToJSON)),
        'error': value['error'],
        'tokenUsage': TokenUsageToJSON(value['tokenUsage']),
        'cost': RunCostToJSON(value['cost']),
    };
}

