/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Provider = {
    Openai: 'openai',
    Gemini: 'gemini',
    Anthropic: 'anthropic'
} as const;
export type Provider = typeof Provider[keyof typeof Provider];


export function instanceOfProvider(value: any): boolean {
    for (const key in Provider) {
        if (Object.prototype.hasOwnProperty.call(Provider, key)) {
            if (Provider[key as keyof typeof Provider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProviderFromJSON(json: any): Provider {
    return ProviderFromJSONTyped(json, false);
}

export function ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provider {
    return json as Provider;
}

export function ProviderToJSON(value?: Provider | null): any {
    return value as any;
}

export function ProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): Provider {
    return value as Provider;
}

