/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { JsonObjectFormat } from './JsonObjectFormat';
import {
    instanceOfJsonObjectFormat,
    JsonObjectFormatFromJSON,
    JsonObjectFormatFromJSONTyped,
    JsonObjectFormatToJSON,
} from './JsonObjectFormat';
import type { JsonSchemaFormat } from './JsonSchemaFormat';
import {
    instanceOfJsonSchemaFormat,
    JsonSchemaFormatFromJSON,
    JsonSchemaFormatFromJSONTyped,
    JsonSchemaFormatToJSON,
} from './JsonSchemaFormat';
import type { TextFormat } from './TextFormat';
import {
    instanceOfTextFormat,
    TextFormatFromJSON,
    TextFormatFromJSONTyped,
    TextFormatToJSON,
} from './TextFormat';

/**
 * @type ResponseFormat
 * 
 * @export
 */
export type ResponseFormat = { type: 'json_object' } & JsonObjectFormat | { type: 'json_schema' } & JsonSchemaFormat | { type: 'text' } & TextFormat;

export function ResponseFormatFromJSON(json: any): ResponseFormat {
    return ResponseFormatFromJSONTyped(json, false);
}

export function ResponseFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseFormat {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'json_object':
            return Object.assign({}, JsonObjectFormatFromJSONTyped(json, true), { type: 'json_object' } as const);
        case 'json_schema':
            return Object.assign({}, JsonSchemaFormatFromJSONTyped(json, true), { type: 'json_schema' } as const);
        case 'text':
            return Object.assign({}, TextFormatFromJSONTyped(json, true), { type: 'text' } as const);
        default:
            return json;
    }
}

export function ResponseFormatToJSON(json: any): any {
    return ResponseFormatToJSONTyped(json, false);
}

export function ResponseFormatToJSONTyped(value?: ResponseFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'json_object':
            return Object.assign({}, JsonObjectFormatToJSON(value), { 'type': 'json_object' } as const);
        case 'json_schema':
            return Object.assign({}, JsonSchemaFormatToJSON(value), { 'type': 'json_schema' } as const);
        case 'text':
            return Object.assign({}, TextFormatToJSON(value), { 'type': 'text' } as const);
        default:
            return value;
    }
}

