/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelCost } from './ModelCost';
import {
    ModelCostFromJSON,
    ModelCostFromJSONTyped,
    ModelCostToJSON,
    ModelCostToJSONTyped,
} from './ModelCost';

/**
 * 
 * @export
 * @interface RunCost
 */
export interface RunCost {
    /**
     * 
     * @type {ModelCost}
     * @memberof RunCost
     */
    success: ModelCost;
    /**
     * 
     * @type {ModelCost}
     * @memberof RunCost
     */
    retries: ModelCost;
    /**
     * 
     * @type {number}
     * @memberof RunCost
     */
    total: number;
}

/**
 * Check if a given object implements the RunCost interface.
 */
export function instanceOfRunCost(value: object): value is RunCost {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('retries' in value) || value['retries'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function RunCostFromJSON(json: any): RunCost {
    return RunCostFromJSONTyped(json, false);
}

export function RunCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunCost {
    if (json == null) {
        return json;
    }
    return {
        
        'success': ModelCostFromJSON(json['success']),
        'retries': ModelCostFromJSON(json['retries']),
        'total': json['total'],
    };
}

export function RunCostToJSON(json: any): RunCost {
    return RunCostToJSONTyped(json, false);
}

export function RunCostToJSONTyped(value?: RunCost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': ModelCostToJSON(value['success']),
        'retries': ModelCostToJSON(value['retries']),
        'total': value['total'],
    };
}

