/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Call custom Python or JavaScript function.
 * @export
 * @interface ScriptCall
 */
export interface ScriptCall {
    /**
     * The language of the script to execute.
     * @type {ScriptCallLanguageEnum}
     * @memberof ScriptCall
     */
    language: ScriptCallLanguageEnum;
    /**
     * The script that this tool executes.
     * @type {string}
     * @memberof ScriptCall
     */
    code: string;
    /**
     * The tool’s name.
     * @type {string}
     * @memberof ScriptCall
     */
    name: string;
    /**
     * The tool’s description.
     * @type {string}
     * @memberof ScriptCall
     */
    description?: string | null;
    /**
     * Whether to stop processing if a tool call fails.
     * @type {boolean}
     * @memberof ScriptCall
     */
    failFast?: boolean;
    /**
     * 
     * @type {ScriptCallTypeEnum}
     * @memberof ScriptCall
     */
    type: ScriptCallTypeEnum;
}


/**
 * @export
 */
export const ScriptCallLanguageEnum = {
    Python: 'python',
    Javascript: 'javascript'
} as const;
export type ScriptCallLanguageEnum = typeof ScriptCallLanguageEnum[keyof typeof ScriptCallLanguageEnum];

/**
 * @export
 */
export const ScriptCallTypeEnum = {
    Script: 'script'
} as const;
export type ScriptCallTypeEnum = typeof ScriptCallTypeEnum[keyof typeof ScriptCallTypeEnum];


/**
 * Check if a given object implements the ScriptCall interface.
 */
export function instanceOfScriptCall(value: object): value is ScriptCall {
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'script') return false;
    
    return true;
}

export function ScriptCallFromJSON(json: any): ScriptCall {
    return ScriptCallFromJSONTyped(json, false);
}

export function ScriptCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScriptCall {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'failFast': json['failFast'] == null ? undefined : json['failFast'],
        'type': json['type'],
    };
}

export function ScriptCallToJSON(json: any): ScriptCall {
    return ScriptCallToJSONTyped(json, false);
}

export function ScriptCallToJSONTyped(value?: ScriptCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'language': value['language'],
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'failFast': value['failFast'],
        'type': value['type'],
    };
}

