/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServiceTier = {
    Auto: 'auto',
    Default: 'default',
    Flex: 'flex',
    Priority: 'priority'
} as const;
export type ServiceTier = typeof ServiceTier[keyof typeof ServiceTier];


export function instanceOfServiceTier(value: any): boolean {
    for (const key in ServiceTier) {
        if (Object.prototype.hasOwnProperty.call(ServiceTier, key)) {
            if (ServiceTier[key as keyof typeof ServiceTier] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServiceTierFromJSON(json: any): ServiceTier {
    return ServiceTierFromJSONTyped(json, false);
}

export function ServiceTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceTier {
    return json as ServiceTier;
}

export function ServiceTierToJSON(value?: ServiceTier | null): any {
    return value as any;
}

export function ServiceTierToJSONTyped(value: any, ignoreDiscriminator: boolean): ServiceTier {
    return value as ServiceTier;
}

