/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A short-lived credential for subscribing to a thread's token stream.
 * @export
 * @interface StreamTokenResponse
 */
export interface StreamTokenResponse {
    /**
     * Bearer token for the streaming endpoint. Safe to hand to a browser — it grants read access to this one thread and nothing else.
     * @type {string}
     * @memberof StreamTokenResponse
     */
    token: string;
    /**
     * Timestamp when the token stops being accepted.
     * @type {Date}
     * @memberof StreamTokenResponse
     */
    expiresAt: Date;
    /**
     * Fully-resolved SSE endpoint for this thread. Connect here with the token as a Bearer credential.
     * @type {string}
     * @memberof StreamTokenResponse
     */
    url: string;
}

/**
 * Check if a given object implements the StreamTokenResponse interface.
 */
export function instanceOfStreamTokenResponse(value: object): value is StreamTokenResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function StreamTokenResponseFromJSON(json: any): StreamTokenResponse {
    return StreamTokenResponseFromJSONTyped(json, false);
}

export function StreamTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expiresAt': (new Date(json['expiresAt'])),
        'url': json['url'],
    };
}

export function StreamTokenResponseToJSON(json: any): StreamTokenResponse {
    return StreamTokenResponseToJSONTyped(json, false);
}

export function StreamTokenResponseToJSONTyped(value?: StreamTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'expiresAt': value['expiresAt'].toISOString(),
        'url': value['url'],
    };
}

