/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Text response format.
 * @export
 * @interface TextFormat
 */
export interface TextFormat {
    /**
     * 
     * @type {TextFormatTypeEnum}
     * @memberof TextFormat
     */
    type: TextFormatTypeEnum;
}


/**
 * @export
 */
export const TextFormatTypeEnum = {
    Text: 'text'
} as const;
export type TextFormatTypeEnum = typeof TextFormatTypeEnum[keyof typeof TextFormatTypeEnum];


/**
 * Check if a given object implements the TextFormat interface.
 */
export function instanceOfTextFormat(value: object): value is TextFormat {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'text') return false;
    
    return true;
}

export function TextFormatFromJSON(json: any): TextFormat {
    return TextFormatFromJSONTyped(json, false);
}

export function TextFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function TextFormatToJSON(json: any): TextFormat {
    return TextFormatToJSONTyped(json, false);
}

export function TextFormatToJSONTyped(value?: TextFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

