/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceTier } from './ServiceTier';
import {
    ServiceTierFromJSON,
    ServiceTierFromJSONTyped,
    ServiceTierToJSON,
    ServiceTierToJSONTyped,
} from './ServiceTier';

/**
 * 
 * @export
 * @interface TokenUsage
 */
export interface TokenUsage {
    /**
     * 
     * @type {number}
     * @memberof TokenUsage
     */
    input: number;
    /**
     * 
     * @type {number}
     * @memberof TokenUsage
     */
    inputCached: number;
    /**
     * 
     * @type {number}
     * @memberof TokenUsage
     */
    output: number;
    /**
     * 
     * @type {number}
     * @memberof TokenUsage
     */
    reasoning: number;
    /**
     * 
     * @type {number}
     * @memberof TokenUsage
     */
    total: number;
    /**
     * 
     * @type {ServiceTier}
     * @memberof TokenUsage
     */
    serviceTier?: ServiceTier;
}



/**
 * Check if a given object implements the TokenUsage interface.
 */
export function instanceOfTokenUsage(value: object): value is TokenUsage {
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('inputCached' in value) || value['inputCached'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('reasoning' in value) || value['reasoning'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function TokenUsageFromJSON(json: any): TokenUsage {
    return TokenUsageFromJSONTyped(json, false);
}

export function TokenUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'],
        'inputCached': json['inputCached'],
        'output': json['output'],
        'reasoning': json['reasoning'],
        'total': json['total'],
        'serviceTier': json['serviceTier'] == null ? undefined : ServiceTierFromJSON(json['serviceTier']),
    };
}

export function TokenUsageToJSON(json: any): TokenUsage {
    return TokenUsageToJSONTyped(json, false);
}

export function TokenUsageToJSONTyped(value?: TokenUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input': value['input'],
        'inputCached': value['inputCached'],
        'output': value['output'],
        'reasoning': value['reasoning'],
        'total': value['total'],
        'serviceTier': ServiceTierToJSON(value['serviceTier']),
    };
}

