/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HttpCall } from './HttpCall';
import {
    instanceOfHttpCall,
    HttpCallFromJSON,
    HttpCallFromJSONTyped,
    HttpCallToJSON,
} from './HttpCall';
import type { KnowledgeSearch } from './KnowledgeSearch';
import {
    instanceOfKnowledgeSearch,
    KnowledgeSearchFromJSON,
    KnowledgeSearchFromJSONTyped,
    KnowledgeSearchToJSON,
} from './KnowledgeSearch';
import type { Mcp } from './Mcp';
import {
    instanceOfMcp,
    McpFromJSON,
    McpFromJSONTyped,
    McpToJSON,
} from './Mcp';
import type { PromptCall } from './PromptCall';
import {
    instanceOfPromptCall,
    PromptCallFromJSON,
    PromptCallFromJSONTyped,
    PromptCallToJSON,
} from './PromptCall';
import type { ScriptCall } from './ScriptCall';
import {
    instanceOfScriptCall,
    ScriptCallFromJSON,
    ScriptCallFromJSONTyped,
    ScriptCallToJSON,
} from './ScriptCall';
import type { WebSearch } from './WebSearch';
import {
    instanceOfWebSearch,
    WebSearchFromJSON,
    WebSearchFromJSONTyped,
    WebSearchToJSON,
} from './WebSearch';
import type { WorkflowCall } from './WorkflowCall';
import {
    instanceOfWorkflowCall,
    WorkflowCallFromJSON,
    WorkflowCallFromJSONTyped,
    WorkflowCallToJSON,
} from './WorkflowCall';

/**
 * @type Tool
 * 
 * @export
 */
export type Tool = { type: 'http' } & HttpCall | { type: 'knowledge_search' } & KnowledgeSearch | { type: 'mcp' } & Mcp | { type: 'prompt' } & PromptCall | { type: 'script' } & ScriptCall | { type: 'web_search' } & WebSearch | { type: 'workflow' } & WorkflowCall;

export function ToolFromJSON(json: any): Tool {
    return ToolFromJSONTyped(json, false);
}

export function ToolFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tool {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'http':
            return Object.assign({}, HttpCallFromJSONTyped(json, true), { type: 'http' } as const);
        case 'knowledge_search':
            return Object.assign({}, KnowledgeSearchFromJSONTyped(json, true), { type: 'knowledge_search' } as const);
        case 'mcp':
            return Object.assign({}, McpFromJSONTyped(json, true), { type: 'mcp' } as const);
        case 'prompt':
            return Object.assign({}, PromptCallFromJSONTyped(json, true), { type: 'prompt' } as const);
        case 'script':
            return Object.assign({}, ScriptCallFromJSONTyped(json, true), { type: 'script' } as const);
        case 'web_search':
            return Object.assign({}, WebSearchFromJSONTyped(json, true), { type: 'web_search' } as const);
        case 'workflow':
            return Object.assign({}, WorkflowCallFromJSONTyped(json, true), { type: 'workflow' } as const);
        default:
            return json;
    }
}

export function ToolToJSON(json: any): any {
    return ToolToJSONTyped(json, false);
}

export function ToolToJSONTyped(value?: Tool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'http':
            return Object.assign({}, HttpCallToJSON(value), { 'type': 'http' } as const);
        case 'knowledge_search':
            return Object.assign({}, KnowledgeSearchToJSON(value), { 'type': 'knowledge_search' } as const);
        case 'mcp':
            return Object.assign({}, McpToJSON(value), { 'type': 'mcp' } as const);
        case 'prompt':
            return Object.assign({}, PromptCallToJSON(value), { 'type': 'prompt' } as const);
        case 'script':
            return Object.assign({}, ScriptCallToJSON(value), { 'type': 'script' } as const);
        case 'web_search':
            return Object.assign({}, WebSearchToJSON(value), { 'type': 'web_search' } as const);
        case 'workflow':
            return Object.assign({}, WorkflowCallToJSON(value), { 'type': 'workflow' } as const);
        default:
            return value;
    }
}

