/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ToolStatus = {
    Ok: 'ok',
    Error: 'error',
    Pending: 'pending'
} as const;
export type ToolStatus = typeof ToolStatus[keyof typeof ToolStatus];


export function instanceOfToolStatus(value: any): boolean {
    for (const key in ToolStatus) {
        if (Object.prototype.hasOwnProperty.call(ToolStatus, key)) {
            if (ToolStatus[key as keyof typeof ToolStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ToolStatusFromJSON(json: any): ToolStatus {
    return ToolStatusFromJSONTyped(json, false);
}

export function ToolStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolStatus {
    return json as ToolStatus;
}

export function ToolStatusToJSON(value?: ToolStatus | null): any {
    return value as any;
}

export function ToolStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ToolStatus {
    return value as ToolStatus;
}

