/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An emit-tool payload, in the position it was produced.
 * @export
 * @interface TranscriptData
 */
export interface TranscriptData {
    /**
     * The emit tool that produced this payload.
     * @type {string}
     * @memberof TranscriptData
     */
    tool: string;
    /**
     * The payload — the tool-call arguments, verbatim.
     * @type {{ [key: string]: any; }}
     * @memberof TranscriptData
     */
    payload: { [key: string]: any; };
    /**
     * 
     * @type {TranscriptDataTypeEnum}
     * @memberof TranscriptData
     */
    type: TranscriptDataTypeEnum;
}


/**
 * @export
 */
export const TranscriptDataTypeEnum = {
    Data: 'data'
} as const;
export type TranscriptDataTypeEnum = typeof TranscriptDataTypeEnum[keyof typeof TranscriptDataTypeEnum];


/**
 * Check if a given object implements the TranscriptData interface.
 */
export function instanceOfTranscriptData(value: object): value is TranscriptData {
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'data') return false;
    
    return true;
}

export function TranscriptDataFromJSON(json: any): TranscriptData {
    return TranscriptDataFromJSONTyped(json, false);
}

export function TranscriptDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscriptData {
    if (json == null) {
        return json;
    }
    return {
        
        'tool': json['tool'],
        'payload': json['payload'],
        'type': json['type'],
    };
}

export function TranscriptDataToJSON(json: any): TranscriptData {
    return TranscriptDataToJSONTyped(json, false);
}

export function TranscriptDataToJSONTyped(value?: TranscriptData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tool': value['tool'],
        'payload': value['payload'],
        'type': value['type'],
    };
}

