/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TranscriptData } from './TranscriptData';
import {
    instanceOfTranscriptData,
    TranscriptDataFromJSON,
    TranscriptDataFromJSONTyped,
    TranscriptDataToJSON,
} from './TranscriptData';
import type { TranscriptText } from './TranscriptText';
import {
    instanceOfTranscriptText,
    TranscriptTextFromJSON,
    TranscriptTextFromJSONTyped,
    TranscriptTextToJSON,
} from './TranscriptText';
import type { TranscriptTool } from './TranscriptTool';
import {
    instanceOfTranscriptTool,
    TranscriptToolFromJSON,
    TranscriptToolFromJSONTyped,
    TranscriptToolToJSON,
} from './TranscriptTool';

/**
 * @type TranscriptItem
 * 
 * @export
 */
export type TranscriptItem = { type: 'data' } & TranscriptData | { type: 'text' } & TranscriptText | { type: 'tool' } & TranscriptTool;

export function TranscriptItemFromJSON(json: any): TranscriptItem {
    return TranscriptItemFromJSONTyped(json, false);
}

export function TranscriptItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscriptItem {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'data':
            return Object.assign({}, TranscriptDataFromJSONTyped(json, true), { type: 'data' } as const);
        case 'text':
            return Object.assign({}, TranscriptTextFromJSONTyped(json, true), { type: 'text' } as const);
        case 'tool':
            return Object.assign({}, TranscriptToolFromJSONTyped(json, true), { type: 'tool' } as const);
        default:
            return json;
    }
}

export function TranscriptItemToJSON(json: any): any {
    return TranscriptItemToJSONTyped(json, false);
}

export function TranscriptItemToJSONTyped(value?: TranscriptItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'data':
            return Object.assign({}, TranscriptDataToJSON(value), { 'type': 'data' } as const);
        case 'text':
            return Object.assign({}, TranscriptTextToJSON(value), { 'type': 'text' } as const);
        case 'tool':
            return Object.assign({}, TranscriptToolToJSON(value), { 'type': 'tool' } as const);
        default:
            return value;
    }
}

