/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolStatus } from './ToolStatus';
import {
    ToolStatusFromJSON,
    ToolStatusFromJSONTyped,
    ToolStatusToJSON,
    ToolStatusToJSONTyped,
} from './ToolStatus';
import type { Citation } from './Citation';
import {
    CitationFromJSON,
    CitationFromJSONTyped,
    CitationToJSON,
    CitationToJSONTyped,
} from './Citation';

/**
 * A tool the model used: its name and how the call ended.
 * @export
 * @interface TranscriptTool
 */
export interface TranscriptTool {
    /**
     * Tool name, as the model called it.
     * @type {string}
     * @memberof TranscriptTool
     */
    name: string;
    /**
     * How the call ended.
     * @type {ToolStatus}
     * @memberof TranscriptTool
     */
    status: ToolStatus;
    /**
     * Search queries the model ran. Only ever populated by the built-in web_search tool.
     * @type {Array<string>}
     * @memberof TranscriptTool
     */
    queries: Array<string>;
    /**
     * Sources this call returned. Only ever populated by the built-in web_search tool.
     * @type {Array<Citation>}
     * @memberof TranscriptTool
     */
    citations: Array<Citation>;
    /**
     * 
     * @type {TranscriptToolTypeEnum}
     * @memberof TranscriptTool
     */
    type: TranscriptToolTypeEnum;
}


/**
 * @export
 */
export const TranscriptToolTypeEnum = {
    Tool: 'tool'
} as const;
export type TranscriptToolTypeEnum = typeof TranscriptToolTypeEnum[keyof typeof TranscriptToolTypeEnum];


/**
 * Check if a given object implements the TranscriptTool interface.
 */
export function instanceOfTranscriptTool(value: object): value is TranscriptTool {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('queries' in value) || value['queries'] === undefined) return false;
    if (!('citations' in value) || value['citations'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'tool') return false;
    
    return true;
}

export function TranscriptToolFromJSON(json: any): TranscriptTool {
    return TranscriptToolFromJSONTyped(json, false);
}

export function TranscriptToolFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscriptTool {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'status': ToolStatusFromJSON(json['status']),
        'queries': json['queries'],
        'citations': ((json['citations'] as Array<any>).map(CitationFromJSON)),
        'type': json['type'],
    };
}

export function TranscriptToolToJSON(json: any): TranscriptTool {
    return TranscriptToolToJSONTyped(json, false);
}

export function TranscriptToolToJSONTyped(value?: TranscriptTool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'status': ToolStatusToJSON(value['status']),
        'queries': value['queries'],
        'citations': ((value['citations'] as Array<any>).map(CitationToJSON)),
        'type': value['type'],
    };
}

