/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Citation } from './Citation';
import {
    CitationFromJSON,
    CitationFromJSONTyped,
    CitationToJSON,
    CitationToJSONTyped,
} from './Citation';

/**
 * A block of assistant text.
 * @export
 * @interface TranscriptText
 */
export interface TranscriptText {
    /**
     * The assistant text.
     * @type {string}
     * @memberof TranscriptText
     */
    content: string;
    /**
     * Sources cited in this block, deduplicated by URL. Empty unless the model cited any.
     * @type {Array<Citation>}
     * @memberof TranscriptText
     */
    citations: Array<Citation>;
    /**
     * 
     * @type {TranscriptTextTypeEnum}
     * @memberof TranscriptText
     */
    type: TranscriptTextTypeEnum;
}


/**
 * @export
 */
export const TranscriptTextTypeEnum = {
    Text: 'text'
} as const;
export type TranscriptTextTypeEnum = typeof TranscriptTextTypeEnum[keyof typeof TranscriptTextTypeEnum];


/**
 * Check if a given object implements the TranscriptText interface.
 */
export function instanceOfTranscriptText(value: object): value is TranscriptText {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('citations' in value) || value['citations'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'text') return false;
    
    return true;
}

export function TranscriptTextFromJSON(json: any): TranscriptText {
    return TranscriptTextFromJSONTyped(json, false);
}

export function TranscriptTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscriptText {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'citations': ((json['citations'] as Array<any>).map(CitationFromJSON)),
        'type': json['type'],
    };
}

export function TranscriptTextToJSON(json: any): TranscriptText {
    return TranscriptTextToJSONTyped(json, false);
}

export function TranscriptTextToJSONTyped(value?: TranscriptText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'citations': ((value['citations'] as Array<any>).map(CitationToJSON)),
        'type': value['type'],
    };
}

