/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type VersionRefIdOrTag
 * Revision ID or version number or tag.
 * @export
 */
export type VersionRefIdOrTag = number | string;

export function VersionRefIdOrTagFromJSON(json: any): VersionRefIdOrTag {
    return VersionRefIdOrTagFromJSONTyped(json, false);
}

export function VersionRefIdOrTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionRefIdOrTag {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function VersionRefIdOrTagToJSON(json: any): any {
    return VersionRefIdOrTagToJSONTyped(json, false);
}

export function VersionRefIdOrTagToJSONTyped(value?: VersionRefIdOrTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

