/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionRefIdOrTag } from './VersionRefIdOrTag';
import {
    VersionRefIdOrTagFromJSON,
    VersionRefIdOrTagFromJSONTyped,
    VersionRefIdOrTagToJSON,
    VersionRefIdOrTagToJSONTyped,
} from './VersionRefIdOrTag';

/**
 * A reference to a revision.
 * @export
 * @interface VersionRef
 */
export interface VersionRef {
    /**
     * Definition – prompt or workflow – ID.
     * @type {string}
     * @memberof VersionRef
     */
    parentId: string;
    /**
     * 
     * @type {VersionRefIdOrTag}
     * @memberof VersionRef
     */
    idOrTag: VersionRefIdOrTag;
}

/**
 * Check if a given object implements the VersionRef interface.
 */
export function instanceOfVersionRef(value: object): value is VersionRef {
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('idOrTag' in value) || value['idOrTag'] === undefined) return false;
    return true;
}

export function VersionRefFromJSON(json: any): VersionRef {
    return VersionRefFromJSONTyped(json, false);
}

export function VersionRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionRef {
    if (json == null) {
        return json;
    }
    return {
        
        'parentId': json['parentId'],
        'idOrTag': VersionRefIdOrTagFromJSON(json['idOrTag']),
    };
}

export function VersionRefToJSON(json: any): VersionRef {
    return VersionRefToJSONTyped(json, false);
}

export function VersionRefToJSONTyped(value?: VersionRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parentId': value['parentId'],
        'idOrTag': VersionRefIdOrTagToJSON(value['idOrTag']),
    };
}

