/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Built-in web search.
 * @export
 * @interface WebSearch
 */
export interface WebSearch {
    /**
     * 
     * @type {Array<string>}
     * @memberof WebSearch
     */
    allowedDomains?: Array<string> | null;
    /**
     * 
     * @type {WebSearchTypeEnum}
     * @memberof WebSearch
     */
    type: WebSearchTypeEnum;
}


/**
 * @export
 */
export const WebSearchTypeEnum = {
    WebSearch: 'web_search'
} as const;
export type WebSearchTypeEnum = typeof WebSearchTypeEnum[keyof typeof WebSearchTypeEnum];


/**
 * Check if a given object implements the WebSearch interface.
 */
export function instanceOfWebSearch(value: object): value is WebSearch {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'web_search') return false;
    
    return true;
}

export function WebSearchFromJSON(json: any): WebSearch {
    return WebSearchFromJSONTyped(json, false);
}

export function WebSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebSearch {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedDomains': json['allowedDomains'] == null ? undefined : json['allowedDomains'],
        'type': json['type'],
    };
}

export function WebSearchToJSON(json: any): WebSearch {
    return WebSearchToJSONTyped(json, false);
}

export function WebSearchToJSONTyped(value?: WebSearch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowedDomains': value['allowedDomains'],
        'type': value['type'],
    };
}

