/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunStatus } from './RunStatus';
import {
    RunStatusFromJSON,
    RunStatusFromJSONTyped,
    RunStatusToJSON,
    RunStatusToJSONTyped,
} from './RunStatus';

/**
 * Webhook payload for finished workflow runs.
 * @export
 * @interface WorkflowRunFinished
 */
export interface WorkflowRunFinished {
    /**
     * Workflow run ID
     * @type {string}
     * @memberof WorkflowRunFinished
     */
    id: string;
    /**
     * Workflow run status
     * @type {RunStatus}
     * @memberof WorkflowRunFinished
     */
    status: RunStatus;
}



/**
 * Check if a given object implements the WorkflowRunFinished interface.
 */
export function instanceOfWorkflowRunFinished(value: object): value is WorkflowRunFinished {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WorkflowRunFinishedFromJSON(json: any): WorkflowRunFinished {
    return WorkflowRunFinishedFromJSONTyped(json, false);
}

export function WorkflowRunFinishedFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRunFinished {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': RunStatusFromJSON(json['status']),
    };
}

export function WorkflowRunFinishedToJSON(json: any): WorkflowRunFinished {
    return WorkflowRunFinishedToJSONTyped(json, false);
}

export function WorkflowRunFinishedToJSONTyped(value?: WorkflowRunFinished | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': RunStatusToJSON(value['status']),
    };
}

