/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunStatus } from './RunStatus';
import {
    RunStatusFromJSON,
    RunStatusFromJSONTyped,
    RunStatusToJSON,
    RunStatusToJSONTyped,
} from './RunStatus';
import type { TokenUsage } from './TokenUsage';
import {
    TokenUsageFromJSON,
    TokenUsageFromJSONTyped,
    TokenUsageToJSON,
    TokenUsageToJSONTyped,
} from './TokenUsage';
import type { RunCost } from './RunCost';
import {
    RunCostFromJSON,
    RunCostFromJSONTyped,
    RunCostToJSON,
    RunCostToJSONTyped,
} from './RunCost';

/**
 * Workflow run status and results.
 * @export
 * @interface WorkflowRun
 */
export interface WorkflowRun {
    /**
     * Workflow run ID.
     * @type {string}
     * @memberof WorkflowRun
     */
    id: string;
    /**
     * Current run status.
     * @type {RunStatus}
     * @memberof WorkflowRun
     */
    status: RunStatus;
    /**
     * Timestamp when the run was created.
     * @type {Date}
     * @memberof WorkflowRun
     */
    createdAt: Date;
    /**
     * Timestamp when the run finished. Null while the run is pending.
     * @type {Date}
     * @memberof WorkflowRun
     */
    finishedAt?: Date | null;
    /**
     * Map of output node names to their values. Empty object while pending.
     * @type {{ [key: string]: string | null; }}
     * @memberof WorkflowRun
     */
    outputs: { [key: string]: string | null; };
    /**
     * List of error messages from failed nodes. Empty array on success.
     * @type {Array<string>}
     * @memberof WorkflowRun
     */
    errors: Array<string>;
    /**
     * Aggregated token usage across the workflow run. Null while pending.
     * @type {TokenUsage}
     * @memberof WorkflowRun
     */
    tokenUsage?: TokenUsage | null;
    /**
     * Aggregated cost breakdown across the workflow run. Null while pending.
     * @type {RunCost}
     * @memberof WorkflowRun
     */
    cost?: RunCost | null;
}



/**
 * Check if a given object implements the WorkflowRun interface.
 */
export function instanceOfWorkflowRun(value: object): value is WorkflowRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('outputs' in value) || value['outputs'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function WorkflowRunFromJSON(json: any): WorkflowRun {
    return WorkflowRunFromJSONTyped(json, false);
}

export function WorkflowRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': RunStatusFromJSON(json['status']),
        'createdAt': (new Date(json['createdAt'])),
        'finishedAt': json['finishedAt'] == null ? undefined : (new Date(json['finishedAt'])),
        'outputs': json['outputs'],
        'errors': json['errors'],
        'tokenUsage': json['tokenUsage'] == null ? undefined : TokenUsageFromJSON(json['tokenUsage']),
        'cost': json['cost'] == null ? undefined : RunCostFromJSON(json['cost']),
    };
}

export function WorkflowRunToJSON(json: any): WorkflowRun {
    return WorkflowRunToJSONTyped(json, false);
}

export function WorkflowRunToJSONTyped(value?: WorkflowRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': RunStatusToJSON(value['status']),
        'createdAt': value['createdAt'].toISOString(),
        'finishedAt': value['finishedAt'] == null ? value['finishedAt'] : value['finishedAt'].toISOString(),
        'outputs': value['outputs'],
        'errors': value['errors'],
        'tokenUsage': TokenUsageToJSON(value['tokenUsage']),
        'cost': RunCostToJSON(value['cost']),
    };
}

