/* tslint:disable */
/* eslint-disable */
/**
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionRef } from './VersionRef';
import {
    VersionRefFromJSON,
    VersionRefFromJSONTyped,
    VersionRefToJSON,
    VersionRefToJSONTyped,
} from './VersionRef';

/**
 * Tool to invoke a workflow.
 * @export
 * @interface WorkflowCall
 */
export interface WorkflowCall {
    /**
     * Referencing the workflow revision either by id or version number or tag.
     * @type {VersionRef}
     * @memberof WorkflowCall
     */
    versionRef: VersionRef;
    /**
     * The tool’s name.
     * @type {string}
     * @memberof WorkflowCall
     */
    name: string;
    /**
     * The tool’s description.
     * @type {string}
     * @memberof WorkflowCall
     */
    description?: string | null;
    /**
     * Whether to stop processing if a tool call fails.
     * @type {boolean}
     * @memberof WorkflowCall
     */
    failFast?: boolean;
    /**
     * 
     * @type {WorkflowCallTypeEnum}
     * @memberof WorkflowCall
     */
    type: WorkflowCallTypeEnum;
}


/**
 * @export
 */
export const WorkflowCallTypeEnum = {
    Workflow: 'workflow'
} as const;
export type WorkflowCallTypeEnum = typeof WorkflowCallTypeEnum[keyof typeof WorkflowCallTypeEnum];


/**
 * Check if a given object implements the WorkflowCall interface.
 */
export function instanceOfWorkflowCall(value: object): value is WorkflowCall {
    if (!('versionRef' in value) || value['versionRef'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'workflow') return false;
    
    return true;
}

export function WorkflowCallFromJSON(json: any): WorkflowCall {
    return WorkflowCallFromJSONTyped(json, false);
}

export function WorkflowCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowCall {
    if (json == null) {
        return json;
    }
    return {
        
        'versionRef': VersionRefFromJSON(json['versionRef']),
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'failFast': json['failFast'] == null ? undefined : json['failFast'],
        'type': json['type'],
    };
}

export function WorkflowCallToJSON(json: any): WorkflowCall {
    return WorkflowCallToJSONTyped(json, false);
}

export function WorkflowCallToJSONTyped(value?: WorkflowCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'versionRef': VersionRefToJSON(value['versionRef']),
        'name': value['name'],
        'description': value['description'],
        'failFast': value['failFast'],
        'type': value['type'],
    };
}

